import os
from autohubble import hubble_query_to_df, PRESTO
from datetime import date
from datetime import datetime
from pathlib import Path
import math
from pdfrw import PdfReader as PdfrwReader, PdfWriter as PdfrwWriter, PdfDict, PdfName, PdfObject, PdfArray
from pypdf import PdfReader as PypdfReader, PdfWriter as PypdfWriter
import pandas as pd
import csv

################################################################################################
# Pre Processing

# folder Configuration
script_directory = os.path.dirname(__file__)
template_pdf = os.path.join(script_directory, 'PerfectRecv_RetReqForm.pdf')
template_csv = os.path.join(script_directory, 'PerfectRecv_template.csv')

output_folder = os.path.join(script_directory, 'output_forms')
date_str = date.today().strftime('%Y_%m_%d')
form_folder = os.path.join(output_folder, f'{date_str}_ach_return')
Path(form_folder).mkdir(parents=True, exist_ok=True)
print(f"\nCreating forms in: {form_folder}")

# blockedfunding_list = input("Please enter the blockedfunding line items: ")
# blockedfunding_list = 'blockedbtfunding_1SYhvCGkNNxmZIfztZB1wojd,	blockedbtfunding_1SYi0CGkNNxmZIfz74tx6a5h,	blockedbtfunding_1SYhtoGkNNxmZIfzXnX9Y2hm,	blockedbtfunding_1SYPRwGkNNxmZIfzKHxMED8a,	blockedbtfunding_1SYhxbGkNNxmZIfzNbi82edr,	blockedbtfunding_1SYhrZGkNNxmZIfzS5XEBWiv,	blockedbtfunding_1SYhuDGkNNxmZIfzDk1vcOxB,	blockedbtfunding_1SYhrqGkNNxmZIfzEQxj5pi5,	blockedbtfunding_1SYhz5GkNNxmZIfzEpHN8SSN,	blockedbtfunding_1SYi08GkNNxmZIfzjDAwPczU,	blockedbtfunding_1SYhrKGkNNxmZIfzQZUR3Mmj,	blockedbtfunding_1SYhxEGkNNxmZIfztSZjHhUI,	blockedbtfunding_1SYPSWGkNNxmZIfzpcpCgMko,	blockedbtfunding_1SYhuVGkNNxmZIfz7Iy5ZTu5,	blockedbtfunding_1SYhxfGkNNxmZIfzP2tYOeHI,	blockedbtfunding_1SYhrxGkNNxmZIfzKYDGsQVu,	blockedbtfunding_1SYhtcGkNNxmZIfz8GjiKozO,	blockedbtfunding_1SYhwqGkNNxmZIfzmcdZnCLK,	blockedbtfunding_1SYi0xGkNNxmZIfzzykLc8CQ,	blockedbtfunding_1SYi0KGkNNxmZIfz2nHt0dnN,	blockedbtfunding_1SYhu1GkNNxmZIfz50G24aoa,	blockedbtfunding_1SYhyJGkNNxmZIfzoiyCX5er,	blockedbtfunding_1SYhrCGkNNxmZIfzRJIm9k3v,	blockedbtfunding_1SYhqlGkNNxmZIfzHAfbSyVh,	blockedbtfunding_1SYPSJGkNNxmZIfzTQsijJfn,	blockedbtfunding_1SYPR6GkNNxmZIfzARAMFhum,	blockedbtfunding_1SYYybGkNNxmZIfzq2Mhrocl,	blockedbtfunding_1SYi15GkNNxmZIfz9HMTdA60,	blockedbtfunding_1SYPSBGkNNxmZIfzVs8mmYuY,	blockedbtfunding_1SYhuxGkNNxmZIfz3NO6WR6T,	blockedbtfunding_1SYhvpGkNNxmZIfzh2gQV1Sq,	blockedbtfunding_1SYhsuGkNNxmZIfzftR4pyLX,	blockedbtfunding_1SYhytGkNNxmZIfzCckTWT3A,	blockedbtfunding_1SYhuhGkNNxmZIfz7p5qDWa2,	blockedbtfunding_1SYi0dGkNNxmZIfznXgK0WZX,	blockedbtfunding_1SYhxYGkNNxmZIfzVZM3s5XG,	blockedbtfunding_1SYhupGkNNxmZIfzk6jS1Ycr,	blockedbtfunding_1SYhvmGkNNxmZIfzq38wCrVE,	blockedbtfunding_1SYhzfGkNNxmZIfzVRHSvigD,	blockedbtfunding_1SYhs1GkNNxmZIfz3n3GOKlt,	blockedbtfunding_1SYhtxGkNNxmZIfzTQ7GL6LF,	blockedbtfunding_1SYhsqGkNNxmZIfzSHO9vIP5,	blockedbtfunding_1SYPQrGkNNxmZIfziuFS2d7F,	blockedbtfunding_1SYhsKGkNNxmZIfzELIdDiXh,	blockedbtfunding_1SYhrmGkNNxmZIfzyYB6rI1I,	blockedbtfunding_1SYhxwGkNNxmZIfzQY3JKKSc,	blockedbtfunding_1SYi0pGkNNxmZIfzcVR8he6P,	blockedbtfunding_1SYPRcGkNNxmZIfzQaEZRdMk,	blockedbtfunding_1SYhveGkNNxmZIfzRtUsio5L,	blockedbtfunding_1SYPS4GkNNxmZIfzg26Jqvl0,	blockedbtfunding_1SYhr5GkNNxmZIfzqliLcPmq,	blockedbtfunding_1SYhqxGkNNxmZIfzwXDaOqkq,	blockedbtfunding_1SYhutGkNNxmZIfzJ8WJfbQl,	blockedbtfunding_1SYhxAGkNNxmZIfzVQyPZWXM,	blockedbtfunding_1SYPRkGkNNxmZIfz2S2ovEs8,	blockedbtfunding_1SYPSNGkNNxmZIfzJZi5RwbU,	blockedbtfunding_1SYhzwGkNNxmZIfzi31rfDsc,	blockedbtfunding_1SYhwmGkNNxmZIfzw7ihzFgD,	blockedbtfunding_1SYhwyGkNNxmZIfz2pUXOSeu,	blockedbtfunding_1SYPRJGkNNxmZIfz8hGB7cSz,	blockedbtfunding_1SYhsyGkNNxmZIfzfc7ts5nS,	blockedbtfunding_1SYPRZGkNNxmZIfzWqJ0Vz71,	blockedbtfunding_1SYhyhGkNNxmZIfzQjJruf7Z,	blockedbtfunding_1SYhv8GkNNxmZIfzlpVteTId,	blockedbtfunding_1SYhu6GkNNxmZIfz0n1MHAUR,	blockedbtfunding_1SYhwKGkNNxmZIfzDBvraDQl,	blockedbtfunding_1SYhsDGkNNxmZIfzRegOJZvf,	blockedbtfunding_1SYhqbGkNNxmZIfz21F0pPkK,	blockedbtfunding_1SYi0OGkNNxmZIfzZh0wkuTV,	blockedbtfunding_1SYhwWGkNNxmZIfz3OI9Al7K,	blockedbtfunding_1SYhylGkNNxmZIfzIzQuikuo,	blockedbtfunding_1SYhvtGkNNxmZIfzrjpoY4yR,	blockedbtfunding_1SYi0aGkNNxmZIfzmIAYJdeG,	blockedbtfunding_1SYhyBGkNNxmZIfzAG4fHUl5,	blockedbtfunding_1SYhxUGkNNxmZIfzZY2ytf3s,	blockedbtfunding_1SYhzHGkNNxmZIfzb4v1yiVz,	blockedbtfunding_1SYhqpGkNNxmZIfzkMSiAgiL,	blockedbtfunding_1SYhqtGkNNxmZIfz36Etm4To,	blockedbtfunding_1SYi0tGkNNxmZIfzRHxpoMC9,	blockedbtfunding_1SYhzPGkNNxmZIfzViaSicOw,	blockedbtfunding_1SYhseGkNNxmZIfzT6yjdqHQ,	blockedbtfunding_1SYPRRGkNNxmZIfzD6iSBy7E,	blockedbtfunding_1SYhxQGkNNxmZIfzqiksI8xH,	blockedbtfunding_1SYi0hGkNNxmZIfzXHWkrwBo,	blockedbtfunding_1SYht6GkNNxmZIfzC7GcxmgT,	blockedbtfunding_1SYhsSGkNNxmZIfz1YrSlw6P,	blockedbtfunding_1SYhzTGkNNxmZIfzRWY1ubZt,	blockedbtfunding_1SYi0WGkNNxmZIfzYn4iPnlp,	blockedbtfunding_1SYhwuGkNNxmZIfzD3o5RwbI,	blockedbtfunding_1SYhvSGkNNxmZIfzemBbFTXa,	blockedbtfunding_1SYhw5GkNNxmZIfzvzqj3B8K,	blockedbtfunding_1SYhuAGkNNxmZIfz2OVTgqLN,	blockedbtfunding_1SYPRBGkNNxmZIfz2r8G0hT3,	blockedbtfunding_1SYhxnGkNNxmZIfzeX3n0Ep0,	blockedbtfunding_1SYhrVGkNNxmZIfzifTvkDhR,	blockedbtfunding_1SYhrGGkNNxmZIfzsk4tqJP3,	blockedbtfunding_1SYhuRGkNNxmZIfzsdz9toPZ,	blockedbtfunding_1SYhyxGkNNxmZIfzuL1kVTf4,	blockedbtfunding_1SYhtEGkNNxmZIfzdgSJBxwX,	blockedbtfunding_1SYPS7GkNNxmZIfz9JP8g1Di'
# blockedfunding_list = 'blockedbtfunding_1SZUxIGkNNxmZIfzVVBxdxX2,	blockedbtfunding_1SZUtSGkNNxmZIfzQcj0yU8E,	blockedbtfunding_1SaAPSGkNNxmZIfzu7VHueyJ,	blockedbtfunding_1SaARaGkNNxmZIfznFOuAckz,	blockedbtfunding_1SYi0GGkNNxmZIfzu9UqF4j9,	blockedbtfunding_1SZUwvGkNNxmZIfzXnULnbWJ,	blockedbtfunding_1SZUw5GkNNxmZIfzJGL4CTkk,	blockedbtfunding_1SYhrOGkNNxmZIfzqXY61lxm,	blockedbtfunding_1SZoH4GkNNxmZIfzQf89V8gX,	blockedbtfunding_1SZrBWGkNNxmZIfz4Dc6d0w6,	blockedbtfunding_1SYi00GkNNxmZIfz7Eabpwmf,	blockedbtfunding_1SaX22GkNNxmZIfz38QzmsTz,	blockedbtfunding_1SZUwjGkNNxmZIfzx88lA8mX,	blockedbtfunding_1SYhr8GkNNxmZIfzh84Xuy0z,	blockedbtfunding_1SYhz1GkNNxmZIfzhRalw4GQ,	blockedbtfunding_1SZUv7GkNNxmZIfzC8zyUIso,	blockedbtfunding_1SYhwDGkNNxmZIfzeWwHmwXZ,	blockedbtfunding_1SZUtKGkNNxmZIfz71FVYFdJ,	blockedbtfunding_1SZUvVGkNNxmZIfze4kPBJIf,	blockedbtfunding_1SYhriGkNNxmZIfzNG0VwQU6,	blockedbtfunding_1SYhwHGkNNxmZIfzWOk1ajFY,	blockedbtfunding_1SYhx2GkNNxmZIfz8nom7P8o,	blockedbtfunding_1SZUvJGkNNxmZIfzJU1LRcDS,	blockedbtfunding_1SZUxBGkNNxmZIfzYYir5ISo,	blockedbtfunding_1SYhvKGkNNxmZIfz6Z25nFyo,	blockedbtfunding_1SYhvGGkNNxmZIfzAmcJUUA1,	blockedbtfunding_1SYhy7GkNNxmZIfzaEdKY38Q,	blockedbtfunding_1SZUsJGkNNxmZIfzEYfL1sb1,	blockedbtfunding_1SYhsmGkNNxmZIfz8j3Pf6KG,	blockedbtfunding_1SZoFbGkNNxmZIfzxG910xpZ,	blockedbtfunding_1SYi11GkNNxmZIfzY1e3TtUJ,	blockedbtfunding_1SZUskGkNNxmZIfzDzNCC45I,	blockedbtfunding_1SZUuQGkNNxmZIfzFkJP7dpy,	blockedbtfunding_1SZUvlGkNNxmZIfzyTa9pUCi,	blockedbtfunding_1SYhwbGkNNxmZIfzzR8YvyQ3,	blockedbtfunding_1SYhuNGkNNxmZIfzvUwKKg0M,	blockedbtfunding_1SZUsVGkNNxmZIfzyKEejtyx,	blockedbtfunding_1SaARWGkNNxmZIfzomIc1J3D,	blockedbtfunding_1SZUt0GkNNxmZIfzVFM4cGhl,	blockedbtfunding_1SYPRgGkNNxmZIfzWCyVqcU6,	blockedbtfunding_1SZoHKGkNNxmZIfzLRpYFN5f,	blockedbtfunding_1SYPR0GkNNxmZIfzAmRRou9k,	blockedbtfunding_1SaX2YGkNNxmZIfzuxOq3SgB,	blockedbtfunding_1SZUuUGkNNxmZIfzwDHr3lO0,	blockedbtfunding_1SYhthGkNNxmZIfzeKC5eNB4,	blockedbtfunding_1SZoHiGkNNxmZIfzr5FRnUh6,	blockedbtfunding_1SZUuAGkNNxmZIfzdvVF5Uvd,	blockedbtfunding_1SZoGwGkNNxmZIfz8UYD02eJ,	blockedbtfunding_1SZUxUGkNNxmZIfzspFFGS5j,	blockedbtfunding_1SZoFrGkNNxmZIfzR2QR10ze,	blockedbtfunding_1SYhudGkNNxmZIfzMAPV5L5M,	blockedbtfunding_1SZUwMGkNNxmZIfzTTkbBOvG,	blockedbtfunding_1SaARhGkNNxmZIfzrdFMICPl,	blockedbtfunding_1SYhqXGkNNxmZIfzslx8fhbH,	blockedbtfunding_1SYhsWGkNNxmZIfzm7SFkzt9,	blockedbtfunding_1SYhs5GkNNxmZIfzrfVDoY1M,	blockedbtfunding_1SYPRVGkNNxmZIfzIMWC49Aa,	blockedbtfunding_1SYPSFGkNNxmZIfzbqOiAI3v,	blockedbtfunding_1SZUtaGkNNxmZIfzHcaOJNM9,	blockedbtfunding_1SZoH8GkNNxmZIfzLMiNMDVJ,	blockedbtfunding_1SYhsHGkNNxmZIfzZnUHisEr,	blockedbtfunding_1SZoHOGkNNxmZIfzCJFfVWZP,	blockedbtfunding_1SZUwIGkNNxmZIfzBYi5xnvf,	blockedbtfunding_1SZUtyGkNNxmZIfzRBQ1FRot,	blockedbtfunding_1SZUsNGkNNxmZIfzUAX2JHMx,	blockedbtfunding_1SZoGsGkNNxmZIfzKSSuUNqh,	blockedbtfunding_1SYhs9GkNNxmZIfzez4mo7nz,	blockedbtfunding_1SYhw1GkNNxmZIfzo1LS7R0x,	blockedbtfunding_1SZUt4GkNNxmZIfz1VD9mDpJ,	blockedbtfunding_1SYhtXGkNNxmZIfzPpGBHfkM,	blockedbtfunding_1SYhxjGkNNxmZIfzMSRmQRXj,	blockedbtfunding_1SZoG3GkNNxmZIfzGfKjrv7N,	blockedbtfunding_1SZUvdGkNNxmZIfzCYFvhuwZ,	blockedbtfunding_1SZoGIGkNNxmZIfzQIAkw53F,	blockedbtfunding_1SZUsRGkNNxmZIfzlf2xfe9W,	blockedbtfunding_1SZUw1GkNNxmZIfz6oOwgyrr,	blockedbtfunding_1SZoFXGkNNxmZIfzGbIJKaSE,	blockedbtfunding_1SYhvxGkNNxmZIfzlhhG0r8j,	blockedbtfunding_1SYhvWGkNNxmZIfz111O1VRW,	blockedbtfunding_1SYVKPGkNNxmZIfz5hfmPT0S,	blockedbtfunding_1SZUxgGkNNxmZIfz8JG8zTi3,	blockedbtfunding_1SYhtTGkNNxmZIfzCRWP9RHO,	blockedbtfunding_1SYhuIGkNNxmZIfzkmZl0VOq,	blockedbtfunding_1SYPRoGkNNxmZIfzbvleqPq6,	blockedbtfunding_1SaX2KGkNNxmZIfzKkud5vpy,	blockedbtfunding_1SZUtmGkNNxmZIfzF5vDSBRY,	blockedbtfunding_1SZUvhGkNNxmZIfz37AFIfRL,	blockedbtfunding_1SZUuIGkNNxmZIfzJ6hZPaeL,	blockedbtfunding_1SZUsFGkNNxmZIfzag0f5qoN,	blockedbtfunding_1SZUsZGkNNxmZIfzxzj220Z4,	blockedbtfunding_1SaAQsGkNNxmZIfzpYF4fXjH,	blockedbtfunding_1SaARlGkNNxmZIfz4CgHVjJr,	blockedbtfunding_1SZoGkGkNNxmZIfzyyd5XKer,	blockedbtfunding_1SaX1eGkNNxmZIfzxUfCfOlw,	blockedbtfunding_1SZoHuGkNNxmZIfzwk0PRc6p,	blockedbtfunding_1SYhwSGkNNxmZIfzeinrY1hX,	blockedbtfunding_1SYPRFGkNNxmZIfzQkDaGdJ1,	blockedbtfunding_1SYhzbGkNNxmZIfz3P5mansA,	blockedbtfunding_1SZUwfGkNNxmZIfzDlmZjGJu,	blockedbtfunding_1SYhxIGkNNxmZIfzI0qXFKrA'
# blockedfunding_list = 'blockedbtfunding_1SatMhGkNNxmZIfzivxJNdkg, blockedbtfunding_1SYi0SGkNNxmZIfzpEPs7gNy, blockedbtfunding_1SZrBbGkNNxmZIfzNourL99D, blockedbtfunding_1SbER3GkNNxmZIfzXxpm1pc4, blockedbtfunding_1SZUsAGkNNxmZIfzpFlcbXuO, blockedbtfunding_1SZUssGkNNxmZIfz9xyQv0fJ, blockedbtfunding_1SZoFnGkNNxmZIfz4YvnATDR, blockedbtfunding_1SZoGQGkNNxmZIfzvlbdTU4u, blockedbtfunding_1SYhr1GkNNxmZIfz77cYr5XE, blockedbtfunding_1SZUvtGkNNxmZIfzVox7ddib, blockedbtfunding_1SZUtuGkNNxmZIfzUqxnvs0B, blockedbtfunding_1SZoFvGkNNxmZIfzipSgP1zF, blockedbtfunding_1SYhviGkNNxmZIfzgTZfFGuf, blockedbtfunding_1SYPQwGkNNxmZIfzWRaDJcHm, blockedbtfunding_1SZUsgGkNNxmZIfzBKBy4TrN, blockedbtfunding_1SaX2cGkNNxmZIfzXckgG7L6, blockedbtfunding_1SatODGkNNxmZIfzt7tRBzWv, blockedbtfunding_1SatMZGkNNxmZIfzBeY7EPEF, blockedbtfunding_1SZUvxGkNNxmZIfzApWcwW0F, blockedbtfunding_1SZoIBGkNNxmZIfzJ7m6l8fS, blockedbtfunding_1SatMyGkNNxmZIfz2lhJAlKP, blockedbtfunding_1SatOfGkNNxmZIfzgslPwK58, blockedbtfunding_1SatObGkNNxmZIfzIWfp5r0f, blockedbtfunding_1SaARHGkNNxmZIfzsRJzbaEz, blockedbtfunding_1SZUvZGkNNxmZIfzl8jSpz13, blockedbtfunding_1SZUwEGkNNxmZIfz0hY5mA3Q, blockedbtfunding_1SZoGMGkNNxmZIfz1ZsAkb0B, blockedbtfunding_1SatO9GkNNxmZIfz5g136Bdw, blockedbtfunding_1SZUteGkNNxmZIfzcQF3aknM, blockedbtfunding_1SZUuzGkNNxmZIfzMyONPh56, blockedbtfunding_1SYPS0GkNNxmZIfz8aA0GvNz, blockedbtfunding_1SYhyFGkNNxmZIfz9NjIqq12, blockedbtfunding_1SZoHGGkNNxmZIfzsLuW45Zz, blockedbtfunding_1SZUtCGkNNxmZIfz6gFGZGS9, blockedbtfunding_1SZUt8GkNNxmZIfzZg2nzBTW, blockedbtfunding_1SaAPiGkNNxmZIfzzYwRBW4R, blockedbtfunding_1SaARdGkNNxmZIfz1BUduhbU, blockedbtfunding_1SYhtAGkNNxmZIfzPd4bamK5, blockedbtfunding_1SYhuZGkNNxmZIfzQ965RXkP, blockedbtfunding_1SYhzDGkNNxmZIfzsE2OpqgN, blockedbtfunding_1SYhz9GkNNxmZIfzZ7qTluZc, blockedbtfunding_1SYhulGkNNxmZIfzMlSMjUMF, blockedbtfunding_1SaX1QGkNNxmZIfzJzWIl3SZ, blockedbtfunding_1SatNCGkNNxmZIfzTHeMmXxU, blockedbtfunding_1SZUswGkNNxmZIfzTo5ZqfCK, blockedbtfunding_1SYhyRGkNNxmZIfz3xLsA5vQ, blockedbtfunding_1SYhsaGkNNxmZIfzHZBg1COK, blockedbtfunding_1SYhtIGkNNxmZIfzEzg0CQUH, blockedbtfunding_1SatNRGkNNxmZIfzUFajppmM, blockedbtfunding_1SZUvBGkNNxmZIfzT0ZI7ovm, blockedbtfunding_1SatOPGkNNxmZIfzwKh0NqL1, blockedbtfunding_1SYhy0GkNNxmZIfzz4VCcPnH, blockedbtfunding_1SYhreGkNNxmZIfzKMFyeTNS, blockedbtfunding_1SYht2GkNNxmZIfzNVeqeCOO, blockedbtfunding_1SYPRsGkNNxmZIfzbSCYOeXV, blockedbtfunding_1SaAPPGkNNxmZIfzwoNVF4hh, blockedbtfunding_1SZoHmGkNNxmZIfzj1urBrmk, blockedbtfunding_1SZUtWGkNNxmZIfzkhj2O6JV, blockedbtfunding_1SZoH0GkNNxmZIfzdTm3wQGZ, blockedbtfunding_1SYhzXGkNNxmZIfzT7IsY2Af, blockedbtfunding_1SZUuYGkNNxmZIfzGoCMDR1C, blockedbtfunding_1SaX1ZGkNNxmZIfzSGMWUxLy, blockedbtfunding_1SZUwnGkNNxmZIfzr5sgTy1W, blockedbtfunding_1SYi0lGkNNxmZIfzob3KJMJc, blockedbtfunding_1SZUxYGkNNxmZIfzQvz2eVsl, blockedbtfunding_1SYhwiGkNNxmZIfzISpn1AER, blockedbtfunding_1SZUvOGkNNxmZIfzGpvykI96, blockedbtfunding_1SYhsiGkNNxmZIfzHAm34Ux6, blockedbtfunding_1SZUufGkNNxmZIfzpXAMdumu, blockedbtfunding_1SaX1yGkNNxmZIfzan8GipQv, blockedbtfunding_1SYhvOGkNNxmZIfzhqvIqxXq, blockedbtfunding_1SZUsoGkNNxmZIfzaRswEmKP, blockedbtfunding_1SZUscGkNNxmZIfzSVejsx25, blockedbtfunding_1SaARpGkNNxmZIfzUe7Tefox, blockedbtfunding_1SaAR9GkNNxmZIfzcqeE3wXd, blockedbtfunding_1SZoIFGkNNxmZIfzmEdRSk3v, blockedbtfunding_1SZUuvGkNNxmZIfz3o1BeNBW, blockedbtfunding_1SbEQXGkNNxmZIfzbh8i7FSl, blockedbtfunding_1SatMEGkNNxmZIfzMZUl8AdA, blockedbtfunding_1SZoHSGkNNxmZIfziqXFd86y, blockedbtfunding_1SbEQIGkNNxmZIfzMwXxF1Gf, blockedbtfunding_1SYhv1GkNNxmZIfzE7Vi6YiN, blockedbtfunding_1SZoI7GkNNxmZIfzRaqMrl0p, blockedbtfunding_1SZUwXGkNNxmZIfzcON6RNm8, blockedbtfunding_1SZUx7GkNNxmZIfznH5u6YVk, blockedbtfunding_1SZoGgGkNNxmZIfz8uYX1UJQ, blockedbtfunding_1SZoFzGkNNxmZIfzTMDrNV7H, blockedbtfunding_1SatOGGkNNxmZIfzICayF1rb, blockedbtfunding_1SYhy3GkNNxmZIfzdbqF9pot, blockedbtfunding_1SZUv3GkNNxmZIfzw54cxKDX, blockedbtfunding_1SYhsOGkNNxmZIfzGKSbQd7e, blockedbtfunding_1SYPSSGkNNxmZIfzube5Nwdn, blockedbtfunding_1SYhweGkNNxmZIfzU665M05Y, blockedbtfunding_1SawcOGkNNxmZIfzBtNG8hbh, blockedbtfunding_1SatMAGkNNxmZIfzWZvsPjet, blockedbtfunding_1SZoFPGkNNxmZIfzBJuWcLg4, blockedbtfunding_1SaX2gGkNNxmZIfzDKUZZkBA, blockedbtfunding_1SZUtqGkNNxmZIfzgk8qhP1O, blockedbtfunding_1SZoI3GkNNxmZIfzZ5hPjuYU, blockedbtfunding_1SZoHqGkNNxmZIfz3AEmVrcv'
# blockedfunding_list = 'blockedbtfunding_1SZUubGkNNxmZIfz1NUQkdLj, blockedbtfunding_1SZUxMGkNNxmZIfz26zrct1m, blockedbtfunding_1SZUujGkNNxmZIfzjnu23F40, blockedbtfunding_1SatNvGkNNxmZIfzAhDb6Ep6, blockedbtfunding_1SZUurGkNNxmZIfz1zepWZ0z, blockedbtfunding_1SZUxkGkNNxmZIfzaLmivaHQ, blockedbtfunding_1SYhvaGkNNxmZIfzccTqXfYk, blockedbtfunding_1SatOXGkNNxmZIfzbCbDcHPl, blockedbtfunding_1SaX1CGkNNxmZIfzOe7fAWp2, blockedbtfunding_1SZUu6GkNNxmZIfzwO056gOQ, blockedbtfunding_1SZUxQGkNNxmZIfzPodOOZJJ, blockedbtfunding_1SZoGUGkNNxmZIfz55TDClW0, blockedbtfunding_1SYhtPGkNNxmZIfzbb8aYuzb, blockedbtfunding_1SZoHzGkNNxmZIfz0f7Je5TP, blockedbtfunding_1SYhrRGkNNxmZIfzZTE0O1Sx, blockedbtfunding_1SaARDGkNNxmZIfzxwcrQ0eA, blockedbtfunding_1SZUwzGkNNxmZIfzxehvahmo, blockedbtfunding_1SZUvpGkNNxmZIfzn8LSGzTk, blockedbtfunding_1SYhtsGkNNxmZIfz0FGmbjz6, blockedbtfunding_1SZUvRGkNNxmZIfzuny307iP, blockedbtfunding_1SYhtLGkNNxmZIfzt1EcnqCs, blockedbtfunding_1SZoIJGkNNxmZIfzeh8swR9B, blockedbtfunding_1SYhxMGkNNxmZIfzGxuWllvP, blockedbtfunding_1SZUtiGkNNxmZIfz1q9eeMVf, blockedbtfunding_1SaX1FGkNNxmZIfzZaYCkzu0, blockedbtfunding_1SYhw9GkNNxmZIfzx1ZvFxSj, blockedbtfunding_1SYPRNGkNNxmZIfzsbadFBgx, blockedbtfunding_1SatOLGkNNxmZIfzR96RynnF, blockedbtfunding_1SYhtkGkNNxmZIfza3fwUvwH, blockedbtfunding_1SYhzLGkNNxmZIfzFcUYoAXI, blockedbtfunding_1SZUtOGkNNxmZIfzMtSaWC98, blockedbtfunding_1SZUvFGkNNxmZIfzxQvHdTNJ, blockedbtfunding_1SZUwbGkNNxmZIfzcOSek3gy, blockedbtfunding_1SYhwOGkNNxmZIfzQnqzSsKy, blockedbtfunding_1SYhxrGkNNxmZIfzVuLQm3S0, blockedbtfunding_1SatNnGkNNxmZIfzQ2QgkuBW, blockedbtfunding_1SZUxFGkNNxmZIfzMLHh2BXq, blockedbtfunding_1SZoGoGkNNxmZIfzoo2PuGjK, blockedbtfunding_1SaX1tGkNNxmZIfz0Bx0D8PJ, blockedbtfunding_1SZUx3GkNNxmZIfzcSTTFvwa, blockedbtfunding_1SYhypGkNNxmZIfzQeJndi4j, blockedbtfunding_1SZUwTGkNNxmZIfzlt82AVsZ, blockedbtfunding_1SbEQMGkNNxmZIfzcQRK0mvC, blockedbtfunding_1SYi04GkNNxmZIfz0nCKhYtB, blockedbtfunding_1SaAQwGkNNxmZIfzcL2jr6HH, blockedbtfunding_1SYhyNGkNNxmZIfz4vDAwu2u, blockedbtfunding_1SYhruGkNNxmZIfzeNZBgChE, blockedbtfunding_1SatOTGkNNxmZIfzvePqJeeg, blockedbtfunding_1SYhznGkNNxmZIfzugZeMGlD, blockedbtfunding_1SYhv4GkNNxmZIfzzzuJ8a25, blockedbtfunding_1SYhx6GkNNxmZIfzxpRXYQqL, blockedbtfunding_1SZoFTGkNNxmZIfz2XZtWQXK, blockedbtfunding_1SZUtGGkNNxmZIfzjVIpUACb, blockedbtfunding_1SZoFfGkNNxmZIfzlHrtK1jR, blockedbtfunding_1SZUxcGkNNxmZIfzHBjnuYOz, blockedbtfunding_1SYhqhGkNNxmZIfzctWzhMF1, blockedbtfunding_1SZUwrGkNNxmZIfzJUcoQPso, blockedbtfunding_1SZUuEGkNNxmZIfz1R8SrcPe, blockedbtfunding_1SZUwAGkNNxmZIfzWpszUFJT, blockedbtfunding_1SatNaGkNNxmZIfztgfPjAld, blockedbtfunding_1SZUunGkNNxmZIfzHQLTeOQm, blockedbtfunding_1SZUu2GkNNxmZIfzNTYps7Iq, blockedbtfunding_1SZoHCGkNNxmZIfzSVaCyFnM, blockedbtfunding_1SZUuMGkNNxmZIfzEoRMnRQd, blockedbtfunding_1SZoFkGkNNxmZIfzhhiySoEV'
# blockedfunding_list = 'blockedbtfunding_1Sc2EQGkNNxmZIfz8QeEdWkf, blockedbtfunding_1Sc2EMGkNNxmZIfz0A1gBek0, blockedbtfunding_1Sc8JdGkNNxmZIfzrADFVkPD, blockedbtfunding_1ScIbSGkNNxmZIfzllLsn11T, blockedbtfunding_1Sc2EhGkNNxmZIfzF3iXSD9t, blockedbtfunding_1Sc2EHGkNNxmZIfzt5XPLXdV, blockedbtfunding_1Sc2EYGkNNxmZIfzCyr2G3Wj, blockedbtfunding_1Sc2EDGkNNxmZIfzU2uVC9AH, blockedbtfunding_1Sc8JiGkNNxmZIfzw4EQCJ4I, blockedbtfunding_1Sc2EdGkNNxmZIfzINrlLNxG, blockedbtfunding_1ScIbOGkNNxmZIfz7fxe9NpH, blockedbtfunding_1Sc2EUGkNNxmZIfzKeo4zbom'
# blockedfunding_list = 'blockedbtfunding_1SfFCmGkNNxmZIfzrFOWZzIJ, blockedbtfunding_1SdQpoGkNNxmZIfzje9aCL9T, blockedbtfunding_1SesZmGkNNxmZIfz9QcrtLMl, blockedbtfunding_1SesZvGkNNxmZIfzi0u8rt2j, blockedbtfunding_1Sh71HGkNNxmZIfze5zjX0Vv, blockedbtfunding_1Sesa2GkNNxmZIfzE9e5uOSk, blockedbtfunding_1ScLQyGkNNxmZIfzkzxV8OsA, blockedbtfunding_1ScLRaGkNNxmZIfz0QpA9STx, blockedbtfunding_1SesaDGkNNxmZIfzpxxA8K68, blockedbtfunding_1SchlVGkNNxmZIfzAY2eU9Ny, blockedbtfunding_1Sd4EmGkNNxmZIfzicKAX0j4, blockedbtfunding_1SfFDBGkNNxmZIfz9nZTozpP, blockedbtfunding_1SfyCdGkNNxmZIfztQsu3uRT, blockedbtfunding_1SesaPGkNNxmZIfzCC0uKlcA, blockedbtfunding_1SfyANGkNNxmZIfzwmvwKs4f, blockedbtfunding_1SdQpEGkNNxmZIfz8M7LEWlf, blockedbtfunding_1SdQqTGkNNxmZIfzLm8tXgfX, blockedbtfunding_1SdQonGkNNxmZIfzPIPQ5ZB7, blockedbtfunding_1ShChnGkNNxmZIfz2fI1Qjjk, blockedbtfunding_1SfFDkGkNNxmZIfzEDHKKuB8, blockedbtfunding_1SeZX2GkNNxmZIfz6rWskSvZ, blockedbtfunding_1SesZOGkNNxmZIfzn045U8mv, blockedbtfunding_1SfbWoGkNNxmZIfzz3CE5gCZ, blockedbtfunding_1SfyAvGkNNxmZIfzVdhXwepj, blockedbtfunding_1SdQpzGkNNxmZIfz7oP5ftuQ, blockedbtfunding_1SfyBDGkNNxmZIfztfnMdiku, blockedbtfunding_1SchliGkNNxmZIfzIjXV6BVL, blockedbtfunding_1Sfy9lGkNNxmZIfzOWkpLRD1, blockedbtfunding_1ScLPOGkNNxmZIfzd3snSf8m, blockedbtfunding_1SgJ4uGkNNxmZIfzRxtvzGze, blockedbtfunding_1SchlrGkNNxmZIfzMOoF0bvO, blockedbtfunding_1SdNqpGkNNxmZIfzsT5qOjOh, blockedbtfunding_1Sc2EUGkNNxmZIfzKeo4zbom, blockedbtfunding_1SfyAKGkNNxmZIfzpS2jr7kb, blockedbtfunding_1SesaIGkNNxmZIfzgeN2sJGb, blockedbtfunding_1SesaRGkNNxmZIfzmxmx2q7j, blockedbtfunding_1ScLRmGkNNxmZIfzYqwRGRH9, blockedbtfunding_1SfFDUGkNNxmZIfzO8shdwUt, blockedbtfunding_1SfbWrGkNNxmZIfz4ebOXsMI, blockedbtfunding_1SfyC5GkNNxmZIfzigYAwgXh, blockedbtfunding_1SfFDrGkNNxmZIfzBxwMpHgW, blockedbtfunding_1Sc2EHGkNNxmZIfzt5XPLXdV, blockedbtfunding_1SesZtGkNNxmZIfzS2gRQxHg, blockedbtfunding_1SeZXJGkNNxmZIfzIjrcl64S, blockedbtfunding_1Sg7McGkNNxmZIfzLH2XrzGI, blockedbtfunding_1Sesa9GkNNxmZIfzDxF98KoY, blockedbtfunding_1Sh71SGkNNxmZIfzgKN2rujm, blockedbtfunding_1Sh71MGkNNxmZIfzF9ezX4Lt, blockedbtfunding_1ScLQKGkNNxmZIfzzjBGxtVm, blockedbtfunding_1ScLP6GkNNxmZIfz5cHpofFX, blockedbtfunding_1SfFCbGkNNxmZIfzxcanVIhW, blockedbtfunding_1ScLQ4GkNNxmZIfzFd2ziIah, blockedbtfunding_1Sd4DrGkNNxmZIfzg8OgiLUU, blockedbtfunding_1ScLQWGkNNxmZIfzr44LlrWo, blockedbtfunding_1SfyCPGkNNxmZIfzPXMeOHbZ, blockedbtfunding_1SfbXRGkNNxmZIfzWEqjvDHh, blockedbtfunding_1SfyCMGkNNxmZIfzRqtiqn8S, blockedbtfunding_1Sd4ENGkNNxmZIfz9jYd920S, blockedbtfunding_1Sh71ZGkNNxmZIfzEoG7vT9t, blockedbtfunding_1SfyA9GkNNxmZIfzvTzxuoxj, blockedbtfunding_1SesZEGkNNxmZIfzQU5r0d5m, blockedbtfunding_1SdljaGkNNxmZIfzCHFN06Ig, blockedbtfunding_1SfbX4GkNNxmZIfzssX0DxBn, blockedbtfunding_1ScLRRGkNNxmZIfzOOzMYZdx, blockedbtfunding_1SfyB0GkNNxmZIfzlT1HRutc, blockedbtfunding_1ScLRBGkNNxmZIfzcCkcABMX, blockedbtfunding_1ScLQiGkNNxmZIfzrpzcZEzf, blockedbtfunding_1Schm0GkNNxmZIfzkzIdQubr, blockedbtfunding_1SesaBGkNNxmZIfzx38ZF1NM, blockedbtfunding_1SdQp2GkNNxmZIfzkvfLWpSR, blockedbtfunding_1Sde65GkNNxmZIfzSVLBW8bf, blockedbtfunding_1SdlkCGkNNxmZIfzVj8CbWG9, blockedbtfunding_1Sd4EeGkNNxmZIfzm5gMQ9La, blockedbtfunding_1SfFDhGkNNxmZIfzwF8ekbXo, blockedbtfunding_1SfyCWGkNNxmZIfzlvwVGjcB, blockedbtfunding_1SfyCCGkNNxmZIfzqiTHljaC, blockedbtfunding_1SdQpUGkNNxmZIfzyYCdAmTL, blockedbtfunding_1SfyA0GkNNxmZIfzelGAEVkp, blockedbtfunding_1SdQp0GkNNxmZIfzvbiVqeE4, blockedbtfunding_1SdQqCGkNNxmZIfz5X2jaPJ0, blockedbtfunding_1SfyC1GkNNxmZIfzxNXmUu67, blockedbtfunding_1SeZXEGkNNxmZIfz0KLVJbMZ, blockedbtfunding_1SfyBjGkNNxmZIfzFfCMg39c, blockedbtfunding_1SesZoGkNNxmZIfz1phIjhJo, blockedbtfunding_1SdljSGkNNxmZIfzvly5BjAB, blockedbtfunding_1ScIbOGkNNxmZIfz7fxe9NpH, blockedbtfunding_1SesaGGkNNxmZIfza4qs5z7W, blockedbtfunding_1SfbXMGkNNxmZIfzwmpwVD8F, blockedbtfunding_1SfodJGkNNxmZIfz5qQfkKAw, blockedbtfunding_1SesZxGkNNxmZIfzT4Akurx8, blockedbtfunding_1SfyC8GkNNxmZIfzTda8PJGP, blockedbtfunding_1SfyA3GkNNxmZIfzdAD48eTR, blockedbtfunding_1SdQqFGkNNxmZIfz7tAGR73k, blockedbtfunding_1ScLQmGkNNxmZIfz8QVOEPFY, blockedbtfunding_1SfyAaGkNNxmZIfzA1uS7xcL, blockedbtfunding_1ScLQaGkNNxmZIfzxiyvL6Gb, blockedbtfunding_1SfbXKGkNNxmZIfzq6OzBQKf, blockedbtfunding_1SgJ4zGkNNxmZIfzXJOvCkCn, blockedbtfunding_1SesZqGkNNxmZIfzMX8aXxEN, blockedbtfunding_1SfyBtGkNNxmZIfzzePX8UJS, blockedbtfunding_1SfyCIGkNNxmZIfzi9pbZnnT, blockedbtfunding_1SesZfGkNNxmZIfzPyVDRsAM, blockedbtfunding_1ScLR7GkNNxmZIfzLWh9zgk1, blockedbtfunding_1SdQqIGkNNxmZIfzWFYstLbt, blockedbtfunding_1Sc2EQGkNNxmZIfz8QeEdWkf, blockedbtfunding_1Sc2EMGkNNxmZIfz0A1gBek0, blockedbtfunding_1ScLRNGkNNxmZIfz7S26vg1g, blockedbtfunding_1ScLRiGkNNxmZIfzCTaXEpCo, blockedbtfunding_1SfyAhGkNNxmZIfzuQlXmxoZ, blockedbtfunding_1ScLRJGkNNxmZIfzuf6Omu79, blockedbtfunding_1SeZX5GkNNxmZIfzNpww6qgr, blockedbtfunding_1Sf5gMGkNNxmZIfzClC3iGYg, blockedbtfunding_1SdQqWGkNNxmZIfzoYuzO7Y0, blockedbtfunding_1SdljdGkNNxmZIfzofYCOL2x, blockedbtfunding_1SfyCAGkNNxmZIfzQsdc4jwb, blockedbtfunding_1Sc2EdGkNNxmZIfzINrlLNxG, blockedbtfunding_1SfyApGkNNxmZIfzN1vPKs0Y, blockedbtfunding_1SfFDeGkNNxmZIfzRr8AHdWI, blockedbtfunding_1SfyBrGkNNxmZIfzIXdMnt9h, blockedbtfunding_1SdQpYGkNNxmZIfzXQSOrX1Q, blockedbtfunding_1Sd4DvGkNNxmZIfz40Kv4dr2, blockedbtfunding_1SfyC3GkNNxmZIfzzbE6mnjg, blockedbtfunding_1SfyAcGkNNxmZIfzCL8fJ3h9, blockedbtfunding_1Sh71XGkNNxmZIfzXSaulna2, blockedbtfunding_1SfyByGkNNxmZIfzdnTtMG9T, blockedbtfunding_1SfyCKGkNNxmZIfzvhP6tRVK, blockedbtfunding_1SesZjGkNNxmZIfzIWhFr6FR, blockedbtfunding_1SdQqPGkNNxmZIfzQbgaMTFf, blockedbtfunding_1SesaKGkNNxmZIfzczILLIFd, blockedbtfunding_1SfyBNGkNNxmZIfzdMFlOaFE, blockedbtfunding_1SfFDoGkNNxmZIfzjdUjrvlF, blockedbtfunding_1Sd4DHGkNNxmZIfzmCTTOcJw, blockedbtfunding_1Sc2EYGkNNxmZIfzCyr2G3Wj, blockedbtfunding_1ScLRWGkNNxmZIfzgYEjLvDW, blockedbtfunding_1SdQqYGkNNxmZIfznMFdtxj8, blockedbtfunding_1SfFDXGkNNxmZIfzgNL5iLAJ, blockedbtfunding_1SfFDbGkNNxmZIfz2sLLEUp9, blockedbtfunding_1SesZLGkNNxmZIfzUDxvRy3a, blockedbtfunding_1SfyBmGkNNxmZIfzVOi5flM6, blockedbtfunding_1SfbWvGkNNxmZIfzhDqI2tyr, blockedbtfunding_1SfyCiGkNNxmZIfzqFcpcg2g, blockedbtfunding_1ScIbSGkNNxmZIfzllLsn11T, blockedbtfunding_1ScLPwGkNNxmZIfz9xsJ7Xoe, blockedbtfunding_1ScLPcGkNNxmZIfzModY9kkE, blockedbtfunding_1SdQqMGkNNxmZIfzk3OXXWOe, blockedbtfunding_1SfFDQGkNNxmZIfzddC0u1qc, blockedbtfunding_1SfbX6GkNNxmZIfzEWv6Nmcw, blockedbtfunding_1SdQp4GkNNxmZIfz8AdANTeZ, blockedbtfunding_1SeZXBGkNNxmZIfzpPM0ZrB5, blockedbtfunding_1SfyCgGkNNxmZIfz6kahC9ur, blockedbtfunding_1SgJ4KGkNNxmZIfzn836GDTy, blockedbtfunding_1Sc2EDGkNNxmZIfzU2uVC9AH, blockedbtfunding_1Sc8JdGkNNxmZIfzrADFVkPD, blockedbtfunding_1SesZCGkNNxmZIfzJFzyglhx, blockedbtfunding_1ScLQqGkNNxmZIfzt9SXtTVW, blockedbtfunding_1ScUc6GkNNxmZIfzJF8wdgBj, blockedbtfunding_1Sesa4GkNNxmZIfz12FsfZve, blockedbtfunding_1SfFDuGkNNxmZIfzPvDpKGLr, blockedbtfunding_1SdHSEGkNNxmZIfzeZfuTpYU, blockedbtfunding_1SfSAKGkNNxmZIfz0PSdMGBJ, blockedbtfunding_1Sc2EhGkNNxmZIfzF3iXSD9t, blockedbtfunding_1SchlGGkNNxmZIfzeEIK05zc, blockedbtfunding_1SfOQEGkNNxmZIfzO965ABkH, blockedbtfunding_1SfFD4GkNNxmZIfzRGTzECrn, blockedbtfunding_1Sd4DzGkNNxmZIfzTwKQpNBe, blockedbtfunding_1SfyBoGkNNxmZIfzdbUtcoCd, blockedbtfunding_1SeZX0GkNNxmZIfzHdL4SEue, blockedbtfunding_1SfbXOGkNNxmZIfzqchsXZmt, blockedbtfunding_1SdQpHGkNNxmZIfz18YFI7Uc, blockedbtfunding_1SdQpCGkNNxmZIfzzoJ1H454, blockedbtfunding_1ScLReGkNNxmZIfzn7VQeUHN, blockedbtfunding_1SfyCRGkNNxmZIfzPylLGmw7, blockedbtfunding_1SfyBwGkNNxmZIfzjfsZ7zzI, blockedbtfunding_1Sh71EGkNNxmZIfzQ5JBToQZ, blockedbtfunding_1SdljPGkNNxmZIfzgp270Luw, blockedbtfunding_1ScLR3GkNNxmZIfz2TULgz2g, blockedbtfunding_1Sh71CGkNNxmZIfzE1DhghM5, blockedbtfunding_1Sd4EEGkNNxmZIfzgCmil1MI, blockedbtfunding_1Sfy9iGkNNxmZIfze2mIPCCj, blockedbtfunding_1SesZzGkNNxmZIfzaaqs1xic, blockedbtfunding_1SfbXTGkNNxmZIfzLInHIDjR, blockedbtfunding_1ScLQeGkNNxmZIfzpw4yEO6b, blockedbtfunding_1SfSAMGkNNxmZIfzbNAWTYOe, blockedbtfunding_1Sd4EaGkNNxmZIfz71uCm4ML, blockedbtfunding_1Sesa6GkNNxmZIfz8FXn9vfw, blockedbtfunding_1ScLRqGkNNxmZIfztQaYmUSJ, blockedbtfunding_1SchmDGkNNxmZIfz3p2WsXSf, blockedbtfunding_1SesZhGkNNxmZIfzC1oMFewN, blockedbtfunding_1SchlwGkNNxmZIfzsfrDCfv3, blockedbtfunding_1Sc8JiGkNNxmZIfzw4EQCJ4I, blockedbtfunding_1SdQqRGkNNxmZIfzEqwh3EO2, blockedbtfunding_1SfyCbGkNNxmZIfzrgsZ6lWV, blockedbtfunding_1Sfy9vGkNNxmZIfzgswbId75, blockedbtfunding_1SfyCGGkNNxmZIfzK7XcaSp8, blockedbtfunding_1SdQopGkNNxmZIfzNNCpPfFL, blockedbtfunding_1ScLQuGkNNxmZIfzqMqgsVQ8, blockedbtfunding_1SgJ4oGkNNxmZIfzusxWCedW, blockedbtfunding_1SfFDxGkNNxmZIfzWd2SkJr0, blockedbtfunding_1SgBGMGkNNxmZIfz9XiTYcwO, blockedbtfunding_1ScupUGkNNxmZIfzv6eVsnAf,blockedbtfunding_1SfyCUGkNNxmZIfzcuIy1dRF, blockedbtfunding_1ScLRFGkNNxmZIfzdkwHztvB, blockedbtfunding_1SfyCZGkNNxmZIfz5UUokRlZ, blockedbtfunding_1Sd4EiGkNNxmZIfzHRKw3tkC, blockedbtfunding_1SesaMGkNNxmZIfzQbxNXHBC, blockedbtfunding_1SdQqKGkNNxmZIfzA6EguDEI, blockedbtfunding_1SgJ5EGkNNxmZIfznEUpqsUo'
# blockedfunding_list = 'blockedbtfunding_1SjxPoGkNNxmZIfzdxmpENZH, blockedbtfunding_1Si84kGkNNxmZIfzLYuPwfA2, blockedbtfunding_1SjxPtGkNNxmZIfzngQeOqYi, blockedbtfunding_1SiqHbGkNNxmZIfzlN6HA8pg, blockedbtfunding_1SmUuXGkNNxmZIfzKL8UQhmS, blockedbtfunding_1SmBhPGkNNxmZIfzoggHVmAh, blockedbtfunding_1SiqFaGkNNxmZIfzCy7R3ELK, blockedbtfunding_1SiYm3GkNNxmZIfziwV8q3b2, blockedbtfunding_1SiYmvGkNNxmZIfzO7LOqwrq, blockedbtfunding_1SiqH5GkNNxmZIfzJ46f0tnj, blockedbtfunding_1SiYmqGkNNxmZIfzfNzH5SMq, blockedbtfunding_1ShPuOGkNNxmZIfzcIvr9bw4, blockedbtfunding_1SjxPEGkNNxmZIfztlSTIcT9, blockedbtfunding_1Sl66vGkNNxmZIfz0b19Sil3, blockedbtfunding_1Sl675GkNNxmZIfzIE5xneaY, blockedbtfunding_1SiqH7GkNNxmZIfzeWRLRtWh, blockedbtfunding_1ShPvNGkNNxmZIfzbi0ZBkZn, blockedbtfunding_1Si84zGkNNxmZIfzjy4jOVcs, blockedbtfunding_1SiqHpGkNNxmZIfzSLs4tzcc, blockedbtfunding_1SjxPKGkNNxmZIfzzfzORZgl, blockedbtfunding_1SkeweGkNNxmZIfzlvwmEh4j, blockedbtfunding_1SjxQ2GkNNxmZIfzmZ7Ce0AU, blockedbtfunding_1ShPuwGkNNxmZIfzLzpKJvaK, blockedbtfunding_1SiqGrGkNNxmZIfzUkayoQYo, blockedbtfunding_1SmBgxGkNNxmZIfznPn8g4gh, blockedbtfunding_1SiqHHGkNNxmZIfz4BC9wmKt, blockedbtfunding_1SiYlxGkNNxmZIfzvKi7mzot, blockedbtfunding_1SiqHtGkNNxmZIfzFBgDnnaN, blockedbtfunding_1SkexMGkNNxmZIfzyxpEbB7L, blockedbtfunding_1SkK3ZGkNNxmZIfzHpc8oFHm, blockedbtfunding_1Si84pGkNNxmZIfzwW5lcHOx, blockedbtfunding_1SjeCWGkNNxmZIfzlP1KVUOS, blockedbtfunding_1SiYmXGkNNxmZIfzAWGZ5B38, blockedbtfunding_1ShPvZGkNNxmZIfzcN109XFP, blockedbtfunding_1SkexSGkNNxmZIfzGIPeAUTQ, blockedbtfunding_1ShPvSGkNNxmZIfzneQvYQgv, blockedbtfunding_1SiqGVGkNNxmZIfzqzEdTyVd, blockedbtfunding_1ShTKzGkNNxmZIfzPOLDOERE, blockedbtfunding_1ShPvUGkNNxmZIfzTwnE2rlB, blockedbtfunding_1SlONaGkNNxmZIfztV1WCYf8, blockedbtfunding_1SmBhTGkNNxmZIfzgFhMrPex, blockedbtfunding_1SiYmtGkNNxmZIfzCGdrC5bj, blockedbtfunding_1SiqI4GkNNxmZIfz7yXlKgAI, blockedbtfunding_1SiYlgGkNNxmZIfzb3pBk3fq, blockedbtfunding_1SiYm8GkNNxmZIfzMXKhan3d, blockedbtfunding_1SiYmTGkNNxmZIfz4ueYbo9P, blockedbtfunding_1SiqHMGkNNxmZIfz273s0B17, blockedbtfunding_1SmUtjGkNNxmZIfzUYqgwJRs, blockedbtfunding_1SiqH0GkNNxmZIfzPPSB9tCm, blockedbtfunding_1SmBhFGkNNxmZIfzY6w0Y2UD, blockedbtfunding_1SmUv0GkNNxmZIfzEoaBj9za, blockedbtfunding_1ShPvbGkNNxmZIfzBmFFUAE8, blockedbtfunding_1SiqG5GkNNxmZIfzQMlDFZfp, blockedbtfunding_1ShPvgGkNNxmZIfzAOwO9Ux5, blockedbtfunding_1SiYn0GkNNxmZIfzjdlhI3IE, blockedbtfunding_1ShmYoGkNNxmZIfzaONKPZfc, blockedbtfunding_1ShmYQGkNNxmZIfzlcJGqXqN, blockedbtfunding_1SjeCSGkNNxmZIfzLhBozkN4, blockedbtfunding_1SiqHCGkNNxmZIfzRLxOWIY9, blockedbtfunding_1ShPv4GkNNxmZIfz2nKXuwtJ, blockedbtfunding_1SiYmeGkNNxmZIfzMiTHLCyY, blockedbtfunding_1SiYmJGkNNxmZIfzPM9IhPhl, blockedbtfunding_1SjeCnGkNNxmZIfzsI5qpVjz, blockedbtfunding_1ShPvQGkNNxmZIfz3cMuT3Le, blockedbtfunding_1SmUupGkNNxmZIfzhTqEeBdE, blockedbtfunding_1Sl67AGkNNxmZIfzEoKxWRPz, blockedbtfunding_1SiYldGkNNxmZIfzOSlOf3Nt, blockedbtfunding_1SiYmcGkNNxmZIfzGiN2KbTE, blockedbtfunding_1SiqHmGkNNxmZIfzSKxk3cGT, blockedbtfunding_1SmUulGkNNxmZIfzYgbgv4l9, blockedbtfunding_1Sl66nGkNNxmZIfzAtdfLrUM, blockedbtfunding_1SiYmHGkNNxmZIfzWEQH0q26, blockedbtfunding_1SjxPmGkNNxmZIfzDzPz8Vdn, blockedbtfunding_1SiqGpGkNNxmZIfzM2WF9Wi5, blockedbtfunding_1SlONVGkNNxmZIfznC7ugwUQ, blockedbtfunding_1SjxPcGkNNxmZIfzZgOOHpul, blockedbtfunding_1SiqGeGkNNxmZIfzNEJsgs6J, blockedbtfunding_1SjxPCGkNNxmZIfziuosIK7M, blockedbtfunding_1Sl66jGkNNxmZIfzmtnzOrLV, blockedbtfunding_1SiqHfGkNNxmZIfzu2wmA46k, blockedbtfunding_1SiYllGkNNxmZIfzDgImWXf3, blockedbtfunding_1ShPv2GkNNxmZIfzaKjSeiG2, blockedbtfunding_1ShPuTGkNNxmZIfzPs4q8THO, blockedbtfunding_1SiqHrGkNNxmZIfzQkmyDYsQ, blockedbtfunding_1SmBhYGkNNxmZIfzTdjpOxuh, blockedbtfunding_1ShPvGGkNNxmZIfzzC0dLcPw, blockedbtfunding_1ShmYqGkNNxmZIfzwJE1O7jv, blockedbtfunding_1SmBhKGkNNxmZIfzkLUIUPqt, blockedbtfunding_1SiYmQGkNNxmZIfzmNNgdjR1, blockedbtfunding_1Sl678GkNNxmZIfzxPQAYDqJ, blockedbtfunding_1SmUuyGkNNxmZIfzX4f2tQTM, blockedbtfunding_1SmBhMGkNNxmZIfzv3JRERQj, blockedbtfunding_1ShPvEGkNNxmZIfztey4AuEf, blockedbtfunding_1SjeCdGkNNxmZIfz23HmLpew, blockedbtfunding_1SiqH3GkNNxmZIfzGe3HwntT, blockedbtfunding_1SkK3mGkNNxmZIfza0jkuG5q, blockedbtfunding_1SjxQ0GkNNxmZIfz5CdFLFU2, blockedbtfunding_1Si84mGkNNxmZIfzQs2Pf5SQ, blockedbtfunding_1SjxP6GkNNxmZIfzff34HosB, blockedbtfunding_1ShPudGkNNxmZIfzyx7XWKEI, blockedbtfunding_1SiqGZGkNNxmZIfzFb9GdTaX, blockedbtfunding_1SiYmMGkNNxmZIfzE0UOluz8, blockedbtfunding_1SkK30GkNNxmZIfz4JcbVp5A, blockedbtfunding_1SiqGCGkNNxmZIfztgWQ7YnI, blockedbtfunding_1SiqFwGkNNxmZIfzM2X68Bno, blockedbtfunding_1ShPurGkNNxmZIfzE8Cr4TqF, blockedbtfunding_1SkK3rGkNNxmZIfzN4j4WYnf, blockedbtfunding_1SiYn7GkNNxmZIfzAgdXtdzi, blockedbtfunding_1SmUuwGkNNxmZIfzL8aNLCnY, blockedbtfunding_1SiYmAGkNNxmZIfziZ3cNmjR, blockedbtfunding_1SmBh3GkNNxmZIfzpnpSHksa, blockedbtfunding_1SkK3EGkNNxmZIfzXHTfJhuU, blockedbtfunding_1ShmXxGkNNxmZIfzPNSlWVED, blockedbtfunding_1SmUugGkNNxmZIfzXywSPLYa, blockedbtfunding_1SiqGMGkNNxmZIfzLQdjdq54, blockedbtfunding_1SjxPxGkNNxmZIfz3c4clc9E, blockedbtfunding_1ShmYmGkNNxmZIfzZoY1l7Hg, blockedbtfunding_1SmUu6GkNNxmZIfzKoKGQYTc, blockedbtfunding_1SmUurGkNNxmZIfzUhzWlg5L, blockedbtfunding_1ShPvdGkNNxmZIfzrzywt6zf, blockedbtfunding_1SiqG8GkNNxmZIfzDfQcZ8XT, blockedbtfunding_1SiYlzGkNNxmZIfzEwBZz4gX, blockedbtfunding_1ShPvCGkNNxmZIfzdpE7nMf3, blockedbtfunding_1SjxPhGkNNxmZIfzCGZrCWL4, blockedbtfunding_1SiqHOGkNNxmZIfzSPULDVNz, blockedbtfunding_1ShPuLGkNNxmZIfzRr08kXi1, blockedbtfunding_1ShmYjGkNNxmZIfziphIosIx, blockedbtfunding_1SiqGSGkNNxmZIfz6ktnVPWc, blockedbtfunding_1SjxPTGkNNxmZIfzOh8VvWbz, blockedbtfunding_1SiqFkGkNNxmZIfzjpkUXVBM, blockedbtfunding_1SiqGyGkNNxmZIfz3pOHahhJ, blockedbtfunding_1SiqGAGkNNxmZIfzYGTb33Ty, blockedbtfunding_1SiYm1GkNNxmZIfzOPz4gqT5, blockedbtfunding_1SiYlZGkNNxmZIfzd9dhBA7k, blockedbtfunding_1SiYmxGkNNxmZIfzdhJfl9Ea, blockedbtfunding_1Sl66tGkNNxmZIfz74E6ZwQY, blockedbtfunding_1SjeCsGkNNxmZIfzvxE0O9qA, blockedbtfunding_1SkewkGkNNxmZIfzDDwGTqN0, blockedbtfunding_1SiqHUGkNNxmZIfzBRYoYxzr, blockedbtfunding_1ShPvpGkNNxmZIfzTZ7r1JDe, blockedbtfunding_1ShjZWGkNNxmZIfztQJV2WX2, blockedbtfunding_1SiqI0GkNNxmZIfzjvU6mMXI, blockedbtfunding_1SiqGiGkNNxmZIfz1EbWBFmF, blockedbtfunding_1SiqHWGkNNxmZIfzVEvUqmpz, blockedbtfunding_1SkexQGkNNxmZIfzDgEfv10O, blockedbtfunding_1SiqGQGkNNxmZIfzHJOT6jiM, blockedbtfunding_1ShmYYGkNNxmZIfzgEYQRYix, blockedbtfunding_1SjeCbGkNNxmZIfzESJb0Wvs, blockedbtfunding_1SjxPRGkNNxmZIfzeuWoJk2M, blockedbtfunding_1SiYmVGkNNxmZIfz0E07aS1v, blockedbtfunding_1SlOMnGkNNxmZIfzs8eah1UI, blockedbtfunding_1SlONAGkNNxmZIfzJ3pnfpKW, blockedbtfunding_1SjxOwGkNNxmZIfzmsaK20pm, blockedbtfunding_1SkK3iGkNNxmZIfzppaqdMSy, blockedbtfunding_1SmBhRGkNNxmZIfzSRqd0bYC, blockedbtfunding_1SmUuuGkNNxmZIfzTmRiMkNk, blockedbtfunding_1ShmYVGkNNxmZIfzfWh3CyXm, blockedbtfunding_1SmBhHGkNNxmZIfzNy9mTCAh, blockedbtfunding_1SiqGbGkNNxmZIfzAF0HvbIm, blockedbtfunding_1ShPvJGkNNxmZIfzPW1aKsKu, blockedbtfunding_1SjxPYGkNNxmZIfzHIe8Flq4, blockedbtfunding_1SkewUGkNNxmZIfzLBko8wlm, blockedbtfunding_1Si84uGkNNxmZIfzkaF2rJOx, blockedbtfunding_1SiYmFGkNNxmZIfzpF8h3dRZ, blockedbtfunding_1ShPubGkNNxmZIfzhv72Vy7b, blockedbtfunding_1SiYlpGkNNxmZIfzhXKCDQA6, blockedbtfunding_1SjxPfGkNNxmZIfzS0A2brOJ, blockedbtfunding_1SiqGkGkNNxmZIfzdeV7fMUQ, blockedbtfunding_1SiqGgGkNNxmZIfzmijLG5LR, blockedbtfunding_1SiqGHGkNNxmZIfz1G1NG5JF, blockedbtfunding_1ShPvkGkNNxmZIfzoJtrSbTT, blockedbtfunding_1SmUunGkNNxmZIfzQIZq9r8F, blockedbtfunding_1ShmY4GkNNxmZIfz4m5pg5Ky, blockedbtfunding_1SiqG1GkNNxmZIfz1CYXA5YL, blockedbtfunding_1SjeClGkNNxmZIfzhKYB8XDj, blockedbtfunding_1SiqHiGkNNxmZIfz7YCpQha8, blockedbtfunding_1SiYm6GkNNxmZIfz66l59BZi, blockedbtfunding_1ShPvnGkNNxmZIfzL6zsPeYO, blockedbtfunding_1SkTCKGkNNxmZIfztd5eLZlh, blockedbtfunding_1SjxPWGkNNxmZIfzAz0ORxn0, blockedbtfunding_1Sl673GkNNxmZIfzZ7St7BxG, blockedbtfunding_1ShPupGkNNxmZIfzg9w6Au99, blockedbtfunding_1SkK3tGkNNxmZIfz3cdgIdTh, blockedbtfunding_1SiqGnGkNNxmZIfzg78E2zfo, blockedbtfunding_1SmUuQGkNNxmZIfzAaB0bLuy, blockedbtfunding_1SiqHRGkNNxmZIfzR7Vq4AXJ, blockedbtfunding_1SiqFpGkNNxmZIfzIzVvqa3R, blockedbtfunding_1ShzxVGkNNxmZIfziBgMMusb, blockedbtfunding_1SiqGJGkNNxmZIfzvmbeKB6M, blockedbtfunding_1SiqFrGkNNxmZIfzBhpI9uXn, blockedbtfunding_1SmUuNGkNNxmZIfz4UOE8F1L, blockedbtfunding_1SmUuGGkNNxmZIfzMJP9MzBx, blockedbtfunding_1ShPvWGkNNxmZIfzUZIKKVrj, blockedbtfunding_1SiYmnGkNNxmZIfzPznU979i, blockedbtfunding_1ShPufGkNNxmZIfzWvlssmkm, blockedbtfunding_1SiYmhGkNNxmZIfztEoGw2DN, blockedbtfunding_1SjxOcGkNNxmZIfzA08V5qpe, blockedbtfunding_1SkexOGkNNxmZIfzg1KEC6zq, blockedbtfunding_1ShmY9GkNNxmZIfzXnNtzUMG, blockedbtfunding_1SmUtrGkNNxmZIfzKUvcxgE2,blockedbtfunding_1ShPuJGkNNxmZIfzSRJab7ss, blockedbtfunding_1SiqHYGkNNxmZIfzAZW32Slh, blockedbtfunding_1SlFmPGkNNxmZIfziDD0PNeK, blockedbtfunding_1SkK3RGkNNxmZIfzbSTjqCYg, blockedbtfunding_1SmBh8GkNNxmZIfznCsTkEEX, blockedbtfunding_1SjxOhGkNNxmZIfzQTSHSqZu, blockedbtfunding_1SiqGEGkNNxmZIfzi3yErZEo, blockedbtfunding_1SmBhDGkNNxmZIfzCQVrH1PL, blockedbtfunding_1SmUubGkNNxmZIfz17mn2kIp, blockedbtfunding_1SjxOqGkNNxmZIfzNhxjJbG5, blockedbtfunding_1SiYmDGkNNxmZIfz3NDw4PpU, blockedbtfunding_1SiYmOGkNNxmZIfz6XhcewFr, blockedbtfunding_1SiYn2GkNNxmZIfzzoxPar2x, blockedbtfunding_1SiYmZGkNNxmZIfzDuxYlFvG, blockedbtfunding_1SmUuUGkNNxmZIfzGeEWcQXL, blockedbtfunding_1ShPv6GkNNxmZIfzJjjFmvRW, blockedbtfunding_1ShPuhGkNNxmZIfzrSwuCKyP, blockedbtfunding_1SiqHEGkNNxmZIfzi5wtXP3Q, blockedbtfunding_1SiYn4GkNNxmZIfzwdTg5jUJ, blockedbtfunding_1SjxPaGkNNxmZIfzIXgKERvh, blockedbtfunding_1SjxPjGkNNxmZIfzWB5QQ0T6, blockedbtfunding_1SmBhVGkNNxmZIfzxJUZJDvU, blockedbtfunding_1SiqHKGkNNxmZIfz3wa59Hxl, blockedbtfunding_1SiqHwGkNNxmZIfzVgpT73h3, blockedbtfunding_1SiYmlGkNNxmZIfzoNxlVFl4, blockedbtfunding_1ShPutGkNNxmZIfz1ge5bbzJ, blockedbtfunding_1SjeCqGkNNxmZIfzUraCpQD1, blockedbtfunding_1SjeCNGkNNxmZIfzT0Q3Rpjk, blockedbtfunding_1ShPv9GkNNxmZIfz3nquxq1J, blockedbtfunding_1SjxPvGkNNxmZIfzW01UyotL, blockedbtfunding_1SjxPqGkNNxmZIfzOTUCBvSk, blockedbtfunding_1ShPuXGkNNxmZIfzS0LjoIRc, blockedbtfunding_1SmUueGkNNxmZIfztK9dNkDU, blockedbtfunding_1SiqHAGkNNxmZIfzLoJWwqEv, blockedbtfunding_1Sl66zGkNNxmZIfz8YEJdubZ, blockedbtfunding_1ShPumGkNNxmZIfzJmm1QbXx, blockedbtfunding_1SiqGwGkNNxmZIfz1nqqFaB4, blockedbtfunding_1SmBhaGkNNxmZIfzdq9KMEWt, blockedbtfunding_1ShmY6GkNNxmZIfzPQ5OQfw4, blockedbtfunding_1SiYlrGkNNxmZIfz5hygMiK3, blockedbtfunding_1SmUu4GkNNxmZIfzqtUe3ScE, blockedbtfunding_1SmUuSGkNNxmZIfzr3qjfdTI, blockedbtfunding_1Si852GkNNxmZIfz24ujd9fc, blockedbtfunding_1SiYluGkNNxmZIfzydpLOpqr, blockedbtfunding_1SiqGXGkNNxmZIfzu5QbZUM6, blockedbtfunding_1SiqFyGkNNxmZIfztl722Hbx, blockedbtfunding_1SiqFgGkNNxmZIfzDKwbDLoR, blockedbtfunding_1SjxPAGkNNxmZIfzKBV00viS, blockedbtfunding_1ShPvLGkNNxmZIfzmrPl6aED, blockedbtfunding_1SiqGuGkNNxmZIfzrNBbfixU, blockedbtfunding_1SiqGOGkNNxmZIfz23FHHae7, blockedbtfunding_1ShmYsGkNNxmZIfzVivTThu0, blockedbtfunding_1SmUuZGkNNxmZIfzFcIP7dpp, blockedbtfunding_1SiqHyGkNNxmZIfzHFerA473, blockedbtfunding_1SmBh1GkNNxmZIfzi5aBM5vN, blockedbtfunding_1SjeCjGkNNxmZIfzPRzxIl00, blockedbtfunding_1ShvtrGkNNxmZIfzJOB1IMb8, blockedbtfunding_1SiqHdGkNNxmZIfzexqWiV4w, blockedbtfunding_1Sl66fGkNNxmZIfzR2KMfWB7, blockedbtfunding_1SiYlXGkNNxmZIfzSNfsOadT, blockedbtfunding_1ShzxSGkNNxmZIfzz7i31i7R, blockedbtfunding_1SiYmjGkNNxmZIfzIy3l5pnx, blockedbtfunding_1SmUuLGkNNxmZIfz6pHCZssJ, blockedbtfunding_1SmUuiGkNNxmZIfzcOS6KARE, blockedbtfunding_1SlONJGkNNxmZIfz8mnBeWOe, blockedbtfunding_1SmBguGkNNxmZIfzJLhNim4f, blockedbtfunding_1ShPviGkNNxmZIfzIXnbCxmx, blockedbtfunding_1SmUuJGkNNxmZIfzQqD95WAq, blockedbtfunding_1SiqG3GkNNxmZIfzoNUfy86E, blockedbtfunding_1SiqHkGkNNxmZIfzh7WJzdE4,blockedbtfunding_1SmrNSGkNNxmZIfzP19t1q2N, blockedbtfunding_1SmrNzGkNNxmZIfz7zOtGaq9, blockedbtfunding_1SmrOCGkNNxmZIfzlW8F5iKb, blockedbtfunding_1SmrN1GkNNxmZIfzb4Il1P1D, blockedbtfunding_1SmrNAGkNNxmZIfzq7AMjg4E, blockedbtfunding_1Sn4AfGkNNxmZIfzeinVCszU'
# blockedfunding_list = 'blockedbtfunding_1Sq7XOGkNNxmZIfzfa8lc3rA, blockedbtfunding_1Sq7YMGkNNxmZIfzVvULtDU7, blockedbtfunding_1Srd18GkNNxmZIfzad76Vy2A, blockedbtfunding_1SnaBnGkNNxmZIfzvOZSpfLB, blockedbtfunding_1Sp24wGkNNxmZIfzuSW5DVmf, blockedbtfunding_1Sq7WQGkNNxmZIfzbubI5D5O, blockedbtfunding_1Sq7YsGkNNxmZIfzHRfqUUrj, blockedbtfunding_1Sq7WhGkNNxmZIfzZgGBjLjd, blockedbtfunding_1Sp25jGkNNxmZIfzSik6bgpM, blockedbtfunding_1SpOZSGkNNxmZIfzdYP8IqpB, blockedbtfunding_1Sq7W5GkNNxmZIfz298a4D3X, blockedbtfunding_1Sq7YdGkNNxmZIfzJElCyB7d, blockedbtfunding_1SrczpGkNNxmZIfzfBmyvf6t, blockedbtfunding_1Sq7YDGkNNxmZIfzrPlUWu1D, blockedbtfunding_1SnaCfGkNNxmZIfzOImRHCOt, blockedbtfunding_1Spl2WGkNNxmZIfzfmn3SeGv, blockedbtfunding_1SnaCtGkNNxmZIfzEWOzb9R7, blockedbtfunding_1SpOZXGkNNxmZIfzyrvGnseG, blockedbtfunding_1Soj1WGkNNxmZIfzH9fdxSDe, blockedbtfunding_1Snum2GkNNxmZIfzRZmN8h0q, blockedbtfunding_1Sp24DGkNNxmZIfzgYs2Z8Mu, blockedbtfunding_1Sq7XzGkNNxmZIfzcnAXODn2, blockedbtfunding_1SrokIGkNNxmZIfzfEbqVqgn, blockedbtfunding_1SqSapGkNNxmZIfzZtVjsAks, blockedbtfunding_1Srd0xGkNNxmZIfzvOxuG2vV, blockedbtfunding_1Snum7GkNNxmZIfzciMLKCcp, blockedbtfunding_1Srd0aGkNNxmZIfzxZU2Y7of, blockedbtfunding_1Sp25mGkNNxmZIfzPJ0UTcuI, blockedbtfunding_1Sp25eGkNNxmZIfzy6KZx9Jx, blockedbtfunding_1SrczxGkNNxmZIfzLv4Qpspi, blockedbtfunding_1SnaDWGkNNxmZIfzpm5fu5Yg, blockedbtfunding_1Srd0fGkNNxmZIfzVmk6nhLo, blockedbtfunding_1SnaDHGkNNxmZIfzDgnOfCvC, blockedbtfunding_1Sp24pGkNNxmZIfzDudap6It, blockedbtfunding_1Sq7WaGkNNxmZIfzVInGKTGw, blockedbtfunding_1Spl2fGkNNxmZIfzelRVMmCT, blockedbtfunding_1Sq7WjGkNNxmZIfzkMtNFEvj, blockedbtfunding_1Srd13GkNNxmZIfzwO5pMCRy, blockedbtfunding_1SnaCwGkNNxmZIfzpbHdoDqK, blockedbtfunding_1SsIWRGkNNxmZIfz0InkXxYV, blockedbtfunding_1Sq7Y6GkNNxmZIfzXYpeg6TK, blockedbtfunding_1SnDh8GkNNxmZIfzBUWafzwt, blockedbtfunding_1Sq7X3GkNNxmZIfzaKsDhz6x, blockedbtfunding_1Sq7XrGkNNxmZIfz8eUfFWSt, blockedbtfunding_1SnulmGkNNxmZIfzwTUXs71x, blockedbtfunding_1SnumZGkNNxmZIfzrFZZRB9d, blockedbtfunding_1SnaBzGkNNxmZIfzUwcgNtJD, blockedbtfunding_1SnjB9GkNNxmZIfzo4rv77rK, blockedbtfunding_1Sp256GkNNxmZIfzcKYY1OuD, blockedbtfunding_1Sq7WlGkNNxmZIfzSZIEvFHJ, blockedbtfunding_1Sq7YWGkNNxmZIfzlDRHlT8J, blockedbtfunding_1Sq7UrGkNNxmZIfzXEXZ0kiG, blockedbtfunding_1Sq7WvGkNNxmZIfz1yJIkjhQ, blockedbtfunding_1SnaBdGkNNxmZIfzs1rutMap, blockedbtfunding_1Sq7XhGkNNxmZIfzKHeUJePe, blockedbtfunding_1SnDhBGkNNxmZIfzd7jF2YEH, blockedbtfunding_1Srd0sGkNNxmZIfzYyyNfZZn, blockedbtfunding_1Srd0DGkNNxmZIfzlwovs4mP, blockedbtfunding_1SnaC6GkNNxmZIfz9MIw8fBC, blockedbtfunding_1Srd04GkNNxmZIfzHcKVfor1, blockedbtfunding_1SnulyGkNNxmZIfzsRLYSvse, blockedbtfunding_1SqKv4GkNNxmZIfzuvanfs9F, blockedbtfunding_1Srd11GkNNxmZIfziGq90MNC, blockedbtfunding_1SpOYQGkNNxmZIfzzQsGMzAL, blockedbtfunding_1SnumAGkNNxmZIfzSdJaRR46, blockedbtfunding_1SpLZzGkNNxmZIfzO6CNCrB3, blockedbtfunding_1Spl25GkNNxmZIfz4wLBsBGv, blockedbtfunding_1SsIW7GkNNxmZIfz1oc3xpjW, blockedbtfunding_1SnaCCGkNNxmZIfzav7gUO6G, blockedbtfunding_1Srd0zGkNNxmZIfzoKYOfOQw, blockedbtfunding_1Snn7OGkNNxmZIfzAAXAmTU8, blockedbtfunding_1Soj1wGkNNxmZIfzYZprOHxJ, blockedbtfunding_1SqSazGkNNxmZIfzysSmvwK0, blockedbtfunding_1Sq7XpGkNNxmZIfzzYQy4AM1, blockedbtfunding_1SsIWgGkNNxmZIfzEgah1kTp, blockedbtfunding_1Sq7XCGkNNxmZIfzwg7uNsE3, blockedbtfunding_1Srd0qGkNNxmZIfzC3NHfclV, blockedbtfunding_1SnaCdGkNNxmZIfzlPOSvQqb, blockedbtfunding_1Sp25ZGkNNxmZIfzkswjI82e, blockedbtfunding_1Sq7XRGkNNxmZIfzreqC66hZ, blockedbtfunding_1Soj1zGkNNxmZIfzxhVkJapk, blockedbtfunding_1Sq7XdGkNNxmZIfzw6KeqD6D, blockedbtfunding_1Soj1eGkNNxmZIfz19LAYTtG, blockedbtfunding_1Srd0hGkNNxmZIfzWNWmEWxP, blockedbtfunding_1SpOZZGkNNxmZIfzylosOsVQ, blockedbtfunding_1Sp259GkNNxmZIfzMzggs8cN, blockedbtfunding_1SnaD4GkNNxmZIfzBbrWMlLY, blockedbtfunding_1Sp25hGkNNxmZIfz9hR1tMH6, blockedbtfunding_1Sp24yGkNNxmZIfzPRVsfjPD, blockedbtfunding_1Sq7VEGkNNxmZIfzZzVgPDNz, blockedbtfunding_1Sp25PGkNNxmZIfzO9kB5ueW, blockedbtfunding_1Sp25IGkNNxmZIfzn1Bw6JlP, blockedbtfunding_1Sp24rGkNNxmZIfzcVfkuv1t, blockedbtfunding_1Sp25BGkNNxmZIfzCKYyKnU1, blockedbtfunding_1Sq7YQGkNNxmZIfzXVgZQzQ6, blockedbtfunding_1Sq7XVGkNNxmZIfzEhWVxePa, blockedbtfunding_1Snum0GkNNxmZIfzcCRpUmvW, blockedbtfunding_1Sp24AGkNNxmZIfzAFy71Alx, blockedbtfunding_1SnDgZGkNNxmZIfzpjTDeEz0, blockedbtfunding_1Sp25UGkNNxmZIfza4MxiCME,blockedbtfunding_1SrczkGkNNxmZIfzQvLRMktS, blockedbtfunding_1SnaCYGkNNxmZIfzAgaQ861w, blockedbtfunding_1SnaDeGkNNxmZIfze71pvfZL, blockedbtfunding_1SnaABGkNNxmZIfzR8A42Otu, blockedbtfunding_1Srw4nGkNNxmZIfzL7KioTT3, blockedbtfunding_1SqSauGkNNxmZIfzqgxDQ1NX, blockedbtfunding_1Spl1dGkNNxmZIfzjalieRWH, blockedbtfunding_1Sq7Y8GkNNxmZIfzNBPxZAVN, blockedbtfunding_1SpOYSGkNNxmZIfzHRdA4UQY, blockedbtfunding_1Sq7X5GkNNxmZIfzHtGEIooj, blockedbtfunding_1SnumXGkNNxmZIfz5QqrgMjK, blockedbtfunding_1SpOZOGkNNxmZIfzVwMhrzfv, blockedbtfunding_1Srd1DGkNNxmZIfzFQd6fkOo, blockedbtfunding_1Sp25WGkNNxmZIfzgCYRFBKo, blockedbtfunding_1SpOZbGkNNxmZIfzvYxl7aWC, blockedbtfunding_1Srd0FGkNNxmZIfzRbuaEO96, blockedbtfunding_1Srw46GkNNxmZIfzo3WkulIp, blockedbtfunding_1Sq7V2GkNNxmZIfzRj19zG6X, blockedbtfunding_1Sq7YFGkNNxmZIfzf00GxeNQ, blockedbtfunding_1Sq7WyGkNNxmZIfzgJgcpuih, blockedbtfunding_1Sq7XLGkNNxmZIfzlqyJbCA5, blockedbtfunding_1Sq7Y1GkNNxmZIfzW2IXOUk2, blockedbtfunding_1Spl1YGkNNxmZIfziKSW2vB2, blockedbtfunding_1SpOYdGkNNxmZIfz0CUtOXxq, blockedbtfunding_1Sq7WtGkNNxmZIfzAnOQKjKj, blockedbtfunding_1Soj1uGkNNxmZIfzymrgCdVd, blockedbtfunding_1SsFOFGkNNxmZIfzBF0zFGNm, blockedbtfunding_1SpOZLGkNNxmZIfz08C8peuO, blockedbtfunding_1Sq7XEGkNNxmZIfzhC1uQAyI, blockedbtfunding_1SnaDTGkNNxmZIfzWX0D1MLA, blockedbtfunding_1Sq7VCGkNNxmZIfzoAVLlD1j, blockedbtfunding_1Sp25NGkNNxmZIfzAlnJ5iQX, blockedbtfunding_1SnumRGkNNxmZIfzMFcKOOaX, blockedbtfunding_1Srd0nGkNNxmZIfzQNjG3pAe, blockedbtfunding_1Srd0KGkNNxmZIfzfRW61dPY, blockedbtfunding_1Srd0IGkNNxmZIfzpl4Fks1A, blockedbtfunding_1SnaAsGkNNxmZIfziT7wrAkt, blockedbtfunding_1Sq7YAGkNNxmZIfzwYNavPWU, blockedbtfunding_1SnDgwGkNNxmZIfzTU4vaGao, blockedbtfunding_1SqSasGkNNxmZIfzL7CoEySi, blockedbtfunding_1Spl2AGkNNxmZIfzbSr72kl5, blockedbtfunding_1Sq7XaGkNNxmZIfziSv2SNBZ, blockedbtfunding_1SnaDNGkNNxmZIfziV3NQ648, blockedbtfunding_1Sq7YJGkNNxmZIfzHrjP8qK0, blockedbtfunding_1Sq7X1GkNNxmZIfzgsjWxb9B, blockedbtfunding_1SnaDRGkNNxmZIfzL3622i9S, blockedbtfunding_1Spl2iGkNNxmZIfzr3mP5VKx, blockedbtfunding_1Sq7WoGkNNxmZIfz2nJhQPOW, blockedbtfunding_1SnaCHGkNNxmZIfzIxB5544I, blockedbtfunding_1SnaAMGkNNxmZIfz0qKUUhMP, blockedbtfunding_1SpOZeGkNNxmZIfzCMVOy6Zh, blockedbtfunding_1SnDhIGkNNxmZIfz8ib1kqoF, blockedbtfunding_1Srd0TGkNNxmZIfzpra3PI40, blockedbtfunding_1Sq7YYGkNNxmZIfz6wl8aD46, blockedbtfunding_1SpOYtGkNNxmZIfztwbI9kAr, blockedbtfunding_1Sq7WfGkNNxmZIfz8nseqkal, blockedbtfunding_1Sp24IGkNNxmZIfzyaNRP9g0, blockedbtfunding_1SpOYrGkNNxmZIfzpqvG1P3v, blockedbtfunding_1Sq7WcGkNNxmZIfz8kat6IR5, blockedbtfunding_1SrokEGkNNxmZIfzCkdrvHpA, blockedbtfunding_1Sq7Y3GkNNxmZIfzpj4OqZhn, blockedbtfunding_1Sp24mGkNNxmZIfzuXGIb9sy, blockedbtfunding_1Sp24LGkNNxmZIfzymzC0257, blockedbtfunding_1Srd0RGkNNxmZIfzV7maIo34, blockedbtfunding_1Srd0BGkNNxmZIfzVCXNnGGW, blockedbtfunding_1SnaAFGkNNxmZIfzph9r51Ml, blockedbtfunding_1Sq7XHGkNNxmZIfzPv9oFf5A, blockedbtfunding_1SnaCmGkNNxmZIfzc2T7FywT, blockedbtfunding_1SsIWOGkNNxmZIfzNPF7DIxZ, blockedbtfunding_1Sq7XAGkNNxmZIfzrb0RiFLw, blockedbtfunding_1SsIWiGkNNxmZIfzzwQCJ2W6, blockedbtfunding_1Sq7VmGkNNxmZIfz02alGPJo, blockedbtfunding_1SnDgeGkNNxmZIfzTUkGNDbi, blockedbtfunding_1SpOYhGkNNxmZIfz6DHJiyXy, blockedbtfunding_1Srd16GkNNxmZIfz5zICZeUD, blockedbtfunding_1SnaDgGkNNxmZIfz2xBt9lA8, blockedbtfunding_1SnaDPGkNNxmZIfzzwSDfbwh, blockedbtfunding_1Sq7XkGkNNxmZIfzyWT6HjZF, blockedbtfunding_1Sp25bGkNNxmZIfzae8nW29D, blockedbtfunding_1Srd0uGkNNxmZIfza69BUBwF, blockedbtfunding_1SqSawGkNNxmZIfzQCD5Ulnr, blockedbtfunding_1Sp25GGkNNxmZIfz2Kr8GBtn, blockedbtfunding_1SsIWbGkNNxmZIfzNabtTyNL, blockedbtfunding_1Sp24kGkNNxmZIfzuW9dFYJG, blockedbtfunding_1Sq7YfGkNNxmZIfz5CwVggtF, blockedbtfunding_1Sq7XfGkNNxmZIfzmSZ7j4xF, blockedbtfunding_1SnaDFGkNNxmZIfzUDDgsYOR, blockedbtfunding_1Sq7YiGkNNxmZIfzl5yFulqe, blockedbtfunding_1SpkY9GkNNxmZIfzxSdGdl7b, blockedbtfunding_1Soj1ZGkNNxmZIfzOC0v022D, blockedbtfunding_1SnaCqGkNNxmZIfzYJGnXZlu, blockedbtfunding_1SnaAfGkNNxmZIfzrLUaGdUm, blockedbtfunding_1SnaCyGkNNxmZIfz8Q8YKUby, blockedbtfunding_1Srd06GkNNxmZIfzvctjguMK, blockedbtfunding_1SsIWkGkNNxmZIfzGBY0FM8B, blockedbtfunding_1SnaCjGkNNxmZIfzceiVCNgf, blockedbtfunding_1SnDhFGkNNxmZIfzIpMca8JO, blockedbtfunding_1Srd1BGkNNxmZIfzXZ4aRdmE, blockedbtfunding_1SnaBHGkNNxmZIfzPGLEFKy4, blockedbtfunding_1SnaCoGkNNxmZIfzQ4nvTrHp,blockedbtfunding_1Sq7WVGkNNxmZIfzIKzYn4QP, blockedbtfunding_1SnaDiGkNNxmZIfzUjSByjYl, blockedbtfunding_1SnaCaGkNNxmZIfzqb0FcbhX, blockedbtfunding_1Sq7XmGkNNxmZIfz60mByVtD, blockedbtfunding_1Sp24tGkNNxmZIfzgzUYHfw1, blockedbtfunding_1Sp25LGkNNxmZIfzRyBfX1rA, blockedbtfunding_1Srd09GkNNxmZIfzFNoKH3bD, blockedbtfunding_1Srw3KGkNNxmZIfzIwEjAwuw, blockedbtfunding_1SnaCKGkNNxmZIfzzpqE23lr, blockedbtfunding_1Spl2lGkNNxmZIfzcPdJFFZ4, blockedbtfunding_1SrczuGkNNxmZIfz7h4CxFeh, blockedbtfunding_1SnaD7GkNNxmZIfzxUunFx7e, blockedbtfunding_1Sq7VVGkNNxmZIfzzwyKDPB6, blockedbtfunding_1SpOZVGkNNxmZIfzj1Udm3pl, blockedbtfunding_1Srw3oGkNNxmZIfzHkVrEvTN, blockedbtfunding_1SnaD0GkNNxmZIfzD6GAHXTE, blockedbtfunding_1Sq7VgGkNNxmZIfzwHw9n29F, blockedbtfunding_1Spl1bGkNNxmZIfzxQJs423a, blockedbtfunding_1SnaAWGkNNxmZIfz25XUo8Si, blockedbtfunding_1Soj1jGkNNxmZIfz7fKnKyDw, blockedbtfunding_1SnaDbGkNNxmZIfzosDnsFbd, blockedbtfunding_1Sq7XJGkNNxmZIfz8AmicN1C, blockedbtfunding_1Srd0MGkNNxmZIfz2B50XCaS, blockedbtfunding_1Sq7UuGkNNxmZIfzisXfYosY, blockedbtfunding_1Srd00GkNNxmZIfzHSuWpmwa, blockedbtfunding_1SsIWdGkNNxmZIfzf5pfy2Yc, blockedbtfunding_1Sq7XtGkNNxmZIfzCGDaFgJa, blockedbtfunding_1Sq7X8GkNNxmZIfzy28KnRUv, blockedbtfunding_1Sq7WAGkNNxmZIfzUrDJAHew, blockedbtfunding_1SnaDAGkNNxmZIfz9LfPLidw, blockedbtfunding_1Srd0VGkNNxmZIfzS3zKxfYL, blockedbtfunding_1SpOZJGkNNxmZIfzIcyh3Ycw, blockedbtfunding_1SnaDCGkNNxmZIfz6O6tHT8Z, blockedbtfunding_1SnjBCGkNNxmZIfzBPxUYxoN, blockedbtfunding_1Sq7WrGkNNxmZIfzHTVyC4vo, blockedbtfunding_1Sq7YaGkNNxmZIfzyK3eXPpG, blockedbtfunding_1Sp25DGkNNxmZIfz7XHP5oRH, blockedbtfunding_1Sq7XXGkNNxmZIfzkA4x6es2, blockedbtfunding_1Srw4rGkNNxmZIfzMv24ibkh, blockedbtfunding_1Sq7WYGkNNxmZIfzgnynYoCE, blockedbtfunding_1Sp24TGkNNxmZIfziAlDdLr1, blockedbtfunding_1Sp251GkNNxmZIfzJy1mAHOH, blockedbtfunding_1SpOZQGkNNxmZIfzWJoNWBVx, blockedbtfunding_1Sq7YlGkNNxmZIfzzDPzg3cw, blockedbtfunding_1SnaBRGkNNxmZIfz8q9igtPI, blockedbtfunding_1Srd0cGkNNxmZIfz3fSdpLTV, blockedbtfunding_1Sq7XvGkNNxmZIfzeVOqWrs8, blockedbtfunding_1SsIWHGkNNxmZIfzXWW4siDf, blockedbtfunding_1Sq7YOGkNNxmZIfzUOVmtBSI, blockedbtfunding_1Sp25SGkNNxmZIfzsfaYbBJE, blockedbtfunding_1SnaChGkNNxmZIfzdLOhXzlp, blockedbtfunding_1Snn7FGkNNxmZIfzXFggFErN, blockedbtfunding_1SnaD2GkNNxmZIfzOF0uHTS4, blockedbtfunding_1SnaAyGkNNxmZIfze0AUS2YO, blockedbtfunding_1Srd0YGkNNxmZIfzEvkvTKSX, blockedbtfunding_1Srd0lGkNNxmZIfzf4e5DOPL, blockedbtfunding_1SnjBGGkNNxmZIfzcYj4fvy3, blockedbtfunding_1Sp24XGkNNxmZIfzULNvR432, blockedbtfunding_1Sq7VZGkNNxmZIfztTyUwHdb, blockedbtfunding_1Srd0jGkNNxmZIfz0ZkGjUCo, blockedbtfunding_1SnaDKGkNNxmZIfzMYRwV2G9, blockedbtfunding_1SnaDZGkNNxmZIfzxWc5M5Lx, blockedbtfunding_1Srw4vGkNNxmZIfzhkYzWigg, blockedbtfunding_1Spl1uGkNNxmZIfzBeB0rvaU, blockedbtfunding_1SnaB0GkNNxmZIfzUDxcdqab, blockedbtfunding_1Sq7XTGkNNxmZIfz2uqgJk8x, blockedbtfunding_1SpOZ4GkNNxmZIfztPoG9kG5, blockedbtfunding_1SnDhDGkNNxmZIfzx3CbsuFL, blockedbtfunding_1Sq7YTGkNNxmZIfzQkaXQo65, blockedbtfunding_1Sq7YHGkNNxmZIfzrPKbjlG3, blockedbtfunding_1Sq7VXGkNNxmZIfzXJNt4IIJ, blockedbtfunding_1Sp25oGkNNxmZIfzEBjevXzH, blockedbtfunding_1Sq7YnGkNNxmZIfzPd8gRdK7, blockedbtfunding_1Spl2nGkNNxmZIfzNWgtC0cc, blockedbtfunding_1Sq7YpGkNNxmZIfzZ5N92QtJ, blockedbtfunding_1Srd0OGkNNxmZIfzjlTKi8FF, blockedbtfunding_1SnDgiGkNNxmZIfz4InNTXnj, blockedbtfunding_1Srw4ZGkNNxmZIfz8SH9OAQE'
blockedfunding_list = 'blockedbtfunding_1SxjWFGkNNxmZIfzYi0z1mVW, blockedbtfunding_1SzXu9GkNNxmZIfzWxxAkGBg, blockedbtfunding_1T0bvtGkNNxmZIfzK4AxEEIZ, blockedbtfunding_1SxjWCGkNNxmZIfzNNyyrkx4, blockedbtfunding_1SzKdSGkNNxmZIfzbTwUAbRG, blockedbtfunding_1SzKdPGkNNxmZIfz4RG4xlfd, blockedbtfunding_1T0H0pGkNNxmZIfzq1IXdPSt, blockedbtfunding_1T1mLcGkNNxmZIfzh05seAxP, blockedbtfunding_1T0H0OGkNNxmZIfzNiTmGHJc, blockedbtfunding_1T1mLxGkNNxmZIfz1EJXKVUH, blockedbtfunding_1SxjWSGkNNxmZIfz2uoZ2yD3, blockedbtfunding_1SzBQUGkNNxmZIfz3UBP4p9T, blockedbtfunding_1SxjWAGkNNxmZIfzL9UQq8Kj, blockedbtfunding_1T1mLsGkNNxmZIfzX2tCC8Ey, blockedbtfunding_1T1mM0GkNNxmZIfz6jBa8K2D, blockedbtfunding_1SzBQIGkNNxmZIfzIpZ5lJf1, blockedbtfunding_1SxjVlGkNNxmZIfzPniCTH9m, blockedbtfunding_1SzBQOGkNNxmZIfzbG7OvOR3, blockedbtfunding_1T0H0wGkNNxmZIfzXnXHaTph, blockedbtfunding_1T0H0VGkNNxmZIfzHJQySoQ3, blockedbtfunding_1T0bvnGkNNxmZIfzeGocr5kV, blockedbtfunding_1T0aWIGkNNxmZIfz0FowP2mE, blockedbtfunding_1SzXtGGkNNxmZIfzHKYd62hm, blockedbtfunding_1Sy4aMGkNNxmZIfzKJUUhIzU, blockedbtfunding_1SxjVzGkNNxmZIfzcFZA4Dh3, blockedbtfunding_1SxjVvGkNNxmZIfz6MGwMvUW, blockedbtfunding_1T0H0fGkNNxmZIfzZD54A03V, blockedbtfunding_1SxjW2GkNNxmZIfzyR4Gan75, blockedbtfunding_1T1mM5GkNNxmZIfzhFMPdYjZ, blockedbtfunding_1T1mM3GkNNxmZIfzWN3wpfq4, blockedbtfunding_1T0H0nGkNNxmZIfzoW1JtLUJ, blockedbtfunding_1SzXtJGkNNxmZIfz4LEO1gQ7, blockedbtfunding_1T0H0kGkNNxmZIfzoM9icAMj, blockedbtfunding_1T0bvcGkNNxmZIfz7x7gMpdn, blockedbtfunding_1T1mLoGkNNxmZIfzibj4JTbt, blockedbtfunding_1T0H0XGkNNxmZIfz1QjGDgXv, blockedbtfunding_1SzuDpGkNNxmZIfzsvpBrnP0, blockedbtfunding_1T0aWCGkNNxmZIfzvYEawlZU, blockedbtfunding_1SysDaGkNNxmZIfzgtGfJvWl, blockedbtfunding_1T0bw1GkNNxmZIfzuUh6rvKJ, blockedbtfunding_1SxjWQGkNNxmZIfzhfGYXYO0, blockedbtfunding_1SysDWGkNNxmZIfzfLGXzsTt, blockedbtfunding_1T0H14GkNNxmZIfzPsFrkOjX, blockedbtfunding_1T0H06GkNNxmZIfzOlHavo0g, blockedbtfunding_1SzBQ4GkNNxmZIfzQIsFxpSb, blockedbtfunding_1SysDNGkNNxmZIfz8Sji3sl7, blockedbtfunding_1T0H09GkNNxmZIfzewduSmTH, blockedbtfunding_1SxjWHGkNNxmZIfzKtltjFuU, blockedbtfunding_1SzuDrGkNNxmZIfzfhdiRUXo, blockedbtfunding_1SysDJGkNNxmZIfzoXrxVGla, blockedbtfunding_1SzuDuGkNNxmZIfzDWdBIbSN, blockedbtfunding_1T1mLlGkNNxmZIfzoUjfoRy5, blockedbtfunding_1SxjW5GkNNxmZIfzhA938c3S, blockedbtfunding_1T0bvgGkNNxmZIfzuY6EwlKt, blockedbtfunding_1SxjWKGkNNxmZIfzhfJ9Mr9g, blockedbtfunding_1SzuDAGkNNxmZIfz4qawyotv, blockedbtfunding_1SysDRGkNNxmZIfzBiM2pBMA, blockedbtfunding_1T1mLgGkNNxmZIfzSryDNkFa, blockedbtfunding_1SzKdCGkNNxmZIfzwCso9Mum, blockedbtfunding_1SxjWNGkNNxmZIfzbOdONpnd, blockedbtfunding_1SysDcGkNNxmZIfzRq34DBLN, blockedbtfunding_1T0H0aGkNNxmZIfzwqk0C2tr, blockedbtfunding_1SxjW7GkNNxmZIfzFFmgRdUl, blockedbtfunding_1T0H0dGkNNxmZIfz6I2ltuJ1, blockedbtfunding_1SzKdEGkNNxmZIfzbtOtj9Ao, blockedbtfunding_1SzXtlGkNNxmZIfzbMyIGPgy, blockedbtfunding_1T0H0iGkNNxmZIfzzLcgRVws'
formatted = ", ".join(f"'{item.strip()}'" for item in blockedfunding_list.split(','))
date_of_request = date.today().strftime('%m/%d/%Y')
requester = 'Ansuman Nayak' 
phone_number = '+91 7619344477'
requester_email = 'ansuman@stripe.com'
company_name = 'Stripe Inc'
group_number = '4063'

################################################################################################
# Creating master data table for processing

sql = f'''
with blocked_bt as (
  select from_unixtime(created) as created, _id as blockedbtfunding, external_id, blocked_reason, resolution_status from payserver_snapshot.blocked_bank_transfer_fundings
  where _id in ({formatted})
), funding_cte as (
  select id as fnm ,incoming_transaction_id, transaction_event_id, funds_activity_event_data.amount.amount as funded_amount, transaction_guaranteed_transaction_id as pytx, funds_activity_event_data.external_id as fpibtvnm from iceberg.h_merchant_banktransfersfpi.sharded_funds_network_model_records
  where 1=1
    and transaction_guaranteed_transaction_id in (select external_id from blocked_bt)
), intxn_cte as (
  select id as intxn, source_id from iceberg.incomingtxndb.incoming_transaction_records
  where 1=1
    and id in (select incoming_transaction_id from funding_cte)
),cashwfibai_cte as ( 
  select id as cash_obj, 
    regexp_extract(file_id,'of_.*') as ops_file,
    line_number, 'WIRE' as type, data,
    cast(data.transaction.amount as bigint)/100.00 as amount,
    regexp_extract(regexp_replace(data.transaction.text, ' ', ''), 'WIREREFERENCE:([0-9]{12})', 1) AS wire_reference,
    regexp_extract(data.transaction.text, 'BNF=(\d+)', 1) as vban,
    regexp_extract(data.transaction.text, 'OGB=([^\n]+)ORG=', 1) AS originating_bank,
    regexp_extract(data.transaction.text, 'ORG=(.*?)(?=RFB=|OBI=|OPI=)', 1) AS originator,
    trim(regexp_extract(data.transaction.text, 'BNF=[0-9]+ ([A-Za-z]+(?:\s+[A-Za-z]+){0,2})',1)) AS receiver,
--     date_format(from_unixtime(data.group_header.as_of_date.millis/1000),'%m/%d/%Y') AS entry_date,
  	cast(from_unixtime(data.group_header.as_of_date.millis/1000) as date) AS entry_date,
    data.transaction.type_code,
    data.transaction.text AS full_description
  from iceberg.cashreportingdb.wells_fargo_intraday_bai_records
  where 1=1
    and id in (select source_id from intxn_cte)
), cashwfpr_cte as (
  select id as cash_obj, 
    regexp_extract(file_id,'of_.*') as ops_file,
    line_number, concat('ACH ',type) as type, 
  cast(coalesce(domestic.entry.amount,international.entry.originating_amount)as bigint)/100.00 as amount,
  coalesce(concat(domestic.entry.originating_dfi_id,domestic.entry.sequence_number),concat(international.entry.originating_dfi_id,international.entry.sequence_number)) as wire_reference,
  coalesce(domestic.entry.account_number,international.entry.account_number) as vban,
  coalesce(domestic.batch_header.company_name, international.batch_header.company_name) as company_name,
  coalesce(domestic.batch_header.company_id, international.batch_header.company_id) as company_id,
  coalesce(domestic.entry.individual_name, international.addendum710.receiver_name) as individual_name,
  domestic.entry.individual_id as individual_id,
--   date_format(from_unixtime(occurred_at_seconds) ,'%m/%d/%Y') as entry_date,
  cast(from_unixtime(occurred_at_seconds) as date) as entry_date,
  date_format(from_unixtime(coalesce(domestic.batch_header.effective_entry_date.millis, international.batch_header.effective_entry_date.millis)/1000), '%m/%d/%Y') as posting_date,
  if(coalesce(domestic.entry.transaction_code, international.entry.transaction_code) in (
      'SAVINGS_PRENOTE_CREDIT',
      'SAVINGS_DEBIT_RETURN',
      'SAVINGS_CREDIT',
      'PRENOTE_DEBIT',
      'PRENOTE_CREDIT',
      'DEBIT_RETURN',
      'CREDIT'),'credit','debit') as type_code
    from iceberg.cashreportingdb.wells_fargo_perfect_receivable_records
  where 1=1
    and id in (select source_id from intxn_cte)
), wire_ach_join as (
  select cash_obj, ops_file, line_number, type_code, type, amount, wire_reference, vban, company_name as originator, individual_name as receiver, entry_date, 
  json_object('company_id' value company_id, 'individual_id' value individual_id) as additional_transaction_info
  from cashwfpr_cte 
  union 
  select cash_obj, ops_file, line_number, type_code, type, amount, wire_reference, vban, originator, receiver, entry_date, 
  json_object('originating_bank' value originating_bank) as additional_transaction_info
  from cashwfibai_cte 
), join_data as (
  select bb.*, fc.*, ic.*, waj.*,
  case
    when waj.entry_date is null then null
    when day_of_week(waj.entry_date) = 6 then date_add('day', 2, waj.entry_date) -- Sat -> Mon
    when day_of_week(waj.entry_date) = 7 then date_add('day', 1, waj.entry_date) -- Sun -> Mon
    else waj.entry_date
  end as entry_date_working
  from blocked_bt bb 
  left join funding_cte fc on fc.pytx = bb.external_id
  left join intxn_cte ic on fc.incoming_transaction_id = ic.intxn
  left join wire_ach_join waj on ic.source_id = waj.cash_obj
)select blockedbtfunding, cash_obj, amount, wire_reference, vban, date_format(entry_date_working ,'%m/%d/%Y') as entry_date, 'Credit' as credit_or_debit, 'Checking' as checking_savings, 'R23--Credit Entry Refused by Receiver' as return_code from join_data
-- where resolution_status = 'pending'
'''

df_data = hubble_query_to_df(sql, PRESTO)

required_columns = ['return_code', 'entry_date', 'credit_or_debit', 'checking_savings', 'vban', 'amount', 'wire_reference']
entry_data = df_data[required_columns]
print(entry_data)

################################################################################################
# PDF Form Filling Functions

def prepare_pdf_data(row_data, index, date_of_request, requester, phone_number):

    
    # Prepare transaction data for this specific item
    data = {}
    item_prefix = f'item{index:02d}.'
    data[f'{item_prefix}code'] = 'R23'
    data[f'{item_prefix}effdate'] = row_data['entry_date']
    data[f'{item_prefix}crdr'] = row_data['credit_or_debit']
    data[f'{item_prefix}chksav'] = row_data['checking_savings']
    data[f'{item_prefix}acct'] = str(row_data['vban'])
    data[f'{item_prefix}amt'] = f"{float(row_data['amount']):.2f}"
    data[f'{item_prefix}trace'] = str(row_data['wire_reference'])
    
    return data


def fill_pdf_form(template_path, output_path, form_data):
    """Fill PDF form using pdfrw library - keeps form editable"""
    try:
        pdf = PdfrwReader(template_path)
        
        print("\nFilling PDF form with data:")
        print(f"Total fields to fill: {len(form_data)}")
        
        # Get annotations from the page
        annotations = pdf.pages[0]['/Annots']
        filled_count = 0
        
        if annotations:
            for annotation in annotations:
                if annotation['/Subtype'] == '/Widget':
                    field_name = annotation['/T']
                    if field_name:
                        # Remove parentheses from field name
                        field_name_clean = field_name[1:-1] if field_name.startswith('(') else field_name
                        
                        if field_name_clean in form_data:
                            value = str(form_data[field_name_clean])
                            # Set the value
                            annotation.update(PdfDict(V=f'{value}'))
                            filled_count += 1
        
        print(f"Successfully filled {filled_count} fields")
        
        # Write the filled PDF
        writer = PdfrwWriter()
        writer.write(output_path, pdf)
        print(f"Successfully created PDF: {output_path}")
        return True
    except Exception as e:
        print(f"Error filling PDF: {e}")
        import traceback
        traceback.print_exc()
        return False

################################################################################################
# CSV Export Function

def export_to_csv(df, output_path):
    """Export remaining transactions to CSV file - simple format"""
    try:
        # Create a copy of the dataframe
        export_df = df.copy()
        
        # Format entry date from YYYY-MM-DD to MM/DD/YYYY
        export_df['entry_date'] = export_df['entry_date'].apply(
            lambda x: pd.to_datetime(x).strftime('%m/%d/%Y') if pd.notna(x) else ''
        )
        
        # Format amount with 2 decimal places
        export_df['amount'] = export_df['amount'].apply(
            lambda x: f"{float(x):.2f}" if pd.notna(x) else ''
        )
        
        # Rename columns to match expected format
        column_mapping = {
            'return_code': 'Return Code',
            'entry_date': 'Effective Date',
            'credit_or_debit': 'Credit/Debit',
            'checking_savings': 'Checking/Savings',
            'vban': 'Perfect Receivables Account Number',
            'amount': 'Dollar Amount',
            'wire_reference': 'Trace Number'
        }
        export_df = export_df.rename(columns=column_mapping)
        
        # Reorder columns
        column_order = [
            'Return Code',
            'Effective Date',
            'Credit/Debit',
            'Checking/Savings',
            'Perfect Receivables Account Number',
            'Dollar Amount',
            'Trace Number'
        ]
        export_df = export_df[column_order]
        
        # Export to CSV
        export_df.to_csv(output_path, index=False)
        
        print(f"Successfully created CSV file: {output_path}")
        return True
    except Exception as e:
        print(f"Error creating CSV file: {e}")
        import traceback
        traceback.print_exc()
        return False
    
################################################################################################
# Email Body Generation Function

def generate_email_body(entry_data, account_number='4941789844'):
    """Generate email body for Wells Fargo return request"""
    
    email_body = f"""Hi Bibiana,

We need to get the following funds returned to their originator, as they were credited to Stripe's account #{account_number}. Please see the transaction details below:

"""
    
    # Add each transaction
    for idx, row in entry_data.iterrows():
        # Format entry date from YYYY-MM-DD to YYYY-MM-DD (or custom format)
        entry_date = row['entry_date']
        if entry_date and '-' in str(entry_date):
            # Keep as YYYY-MM-DD or convert to MM/DD/YYYY
            parts = str(entry_date).split('-')
            if len(parts) == 3:
                entry_date = f"{parts[0]}-{parts[1]}-{parts[2]}"  # YYYY-MM-DD
                # Or use: entry_date = f"{parts[1]}/{parts[2]}/{parts[0]}"  # MM/DD/YYYY
        
        # Extract reason from return code
        return_code_full = row['return_code']
        if '--' in return_code_full:
            reason = return_code_full.split('--')[1]
        else:
            reason = return_code_full
        
        # Extract sequence number (last part of wire_reference)
        wire_reference = str(row['wire_reference'])
        sequence_number = wire_reference[-7:] if len(wire_reference) >= 7 else wire_reference
        
        transaction_num = idx + 1
        email_body += f"""Transaction {transaction_num}:
Amount: ${float(row['amount']):.2f}
Effective Date: {entry_date}
VBAN: {row['vban']}
Sequence number: {sequence_number}
Reason: {reason}

"""
    
    email_body += """Let me know if you have any questions!
Thank you"""
    
    return email_body


################################################################################################
# PDF Transaction Summary Function

def generate_pdf_transaction_summary(entry_data, pdf_count=10):
    """Generate a summary of transactions that went into the PDF"""
    
    actual_count = min(pdf_count, len(entry_data))
    pdf_transactions = entry_data.iloc[:actual_count]
    
    summary = f"""
{'='*80}
PDF TRANSACTION SUMMARY
{'='*80}
Total transactions in PDF: {actual_count}

"""
    
    for idx, row in pdf_transactions.iterrows():
        # Format entry date
        entry_date = row['entry_date']
        if entry_date and '-' in str(entry_date):
            parts = str(entry_date).split('-')
            if len(parts) == 3:
                entry_date = f"{parts[1]}/{parts[2]}/{parts[0]}"
        
        # Extract return code
        return_code_full = row['return_code']
        return_code = return_code_full.split('--')[0] if '--' in return_code_full else return_code_full
        
        transaction_num = idx + 1
        summary += f"""Transaction {transaction_num}:
  Return Code:    {return_code}
  Effective Date: {entry_date}
  Credit/Debit:   {row['credit_or_debit']}
  Account Type:   {row['checking_savings']}
  VBAN:           {row['vban']}
  Amount:         ${float(row['amount']):.2f}
  Trace Number:   {row['wire_reference']}
  Full Reason:    {return_code_full}

"""
    
    summary += f"{'='*80}\n"
    
    return summary

################################################################################################
# Excelsior CSV Export Function

def generate_excelsior_csv(df_data, output_path, account='spc-usd-fbo-wf-us-9844'):
    """Generate Excelsior CSV file for accounting entries"""
    try:
        from datetime import timedelta
        
        # Calculate date (current date + 2 days)
        excelsior_date = (date.today() + timedelta(days=2)).strftime('%Y-%m-%d')
        
        # Create excelsior data
        excelsior_data = []
        
        for idx, row in df_data.iterrows():
            # Convert amount to minor units (cents)
            amount_cents = int(float(row['amount']) * 100)
            amount_monetary = f"-{amount_cents} usd"
            
            # Get blockedbtfunding ID
            blockedbtfunding_id = row.get('blockedbtfunding', '')
            if not blockedbtfunding_id and 'blockedbtfunding' not in df_data.columns:
                # If blockedbtfunding column doesn't exist, use a placeholder
                blockedbtfunding_id = f"blockedbtfunding_{idx+1}"
            
            storytime = f"Wells Fargo ach return - {blockedbtfunding_id}"
            
            excelsior_row = {
                'amount_monetary': amount_monetary,
                'account': account,
                'date': excelsior_date,
                'storytime': storytime,
                'category': 'payment_provider_funding_wells',
                'gl_account': '',  # Empty/null
                'label': 'wells_ach_perfect_receivable_return'
            }
            
            excelsior_data.append(excelsior_row)
        
        # Create DataFrame
        excelsior_df = pd.DataFrame(excelsior_data)
        
        # Export to CSV
        excelsior_df.to_csv(output_path, index=False)
        
        print(f"Successfully created Excelsior CSV file: {output_path}")
        print(f"  - Total entries: {len(excelsior_data)}")
        print(f"  - Date used: {excelsior_date}")
        print(f"  - Account: {account}")
        
        return True
    except Exception as e:
        print(f"Error creating Excelsior CSV file: {e}")
        import traceback
        traceback.print_exc()
        return False

################################################################################################
# Main Processing

def process_transactions(entry_data, form_folder, date_of_request, requester, phone_number, 
                        company_name, group_number, df_data):
    """Process transactions: first 10 to PDF, rest to CSV, plus Excelsior CSV"""
    
    total_transactions = len(entry_data)
    print(f"\nTotal transactions to process: {total_transactions}")
    
    if total_transactions == 0:
        print("No transactions to process!")
        return
    
    # Process first 10 transactions for PDF
    pdf_count = min(10, total_transactions)
    
    if pdf_count > 0:
        print(f"\nProcessing first {pdf_count} transactions for PDF form...")
        
        # Prepare all form data - start with header fields
        all_form_data = {
            'req.date': date_of_request,
            'req.requestor': requester,
            'req.phone': phone_number,
            'req.company': company_name,
            'req.group': group_number,
        }
        
        # Add each transaction
        for idx in range(pdf_count):
            row = entry_data.iloc[idx]
            transaction_data = prepare_pdf_data(row, idx + 1, date_of_request, requester, phone_number)
            all_form_data.update(transaction_data)
        
        # Fill and save PDF
        output_pdf = os.path.join(form_folder, f'ACH_Return_Request_{date_str}.pdf')
        fill_pdf_form(template_pdf, output_pdf, all_form_data)
        
        # Generate PDF transaction summary
        pdf_summary = generate_pdf_transaction_summary(entry_data, pdf_count)
        print(pdf_summary)
        
        # Save summary to file
        summary_file = os.path.join(form_folder, f'PDF_Transaction_Summary_{date_str}.txt')
        with open(summary_file, 'w') as f:
            f.write(pdf_summary)
        print(f"PDF transaction summary saved to: {summary_file}")
    
    # Process remaining transactions for CSV
    if total_transactions > 10:
        remaining_count = total_transactions - 10
        print(f"\nProcessing remaining {remaining_count} transactions for CSV...")
        
        remaining_data = entry_data.iloc[10:].reset_index(drop=True)
        output_csv = os.path.join(form_folder, f'ACH_Return_Request_Additional_{date_str}.csv')
        export_to_csv(remaining_data, output_csv)
    
    # Generate Excelsior CSV for ALL transactions
    print("\n" + "="*80)
    print("GENERATING EXCELSIOR CSV")
    print("="*80)
    excelsior_csv = os.path.join(form_folder, f'Excelsior_ACH_Returns_{date_str}.csv')
    generate_excelsior_csv(df_data, excelsior_csv)
    
    # Generate email body for ALL transactions
    print("\n" + "="*80)
    print("GENERATING EMAIL BODY")
    print("="*80)
    email_body = generate_email_body(entry_data)
    # print(email_body)
    
    # Save email body to file
    email_file = os.path.join(form_folder, f'Email_Body_{date_str}.txt')
    with open(email_file, 'w') as f:
        f.write(email_body)
    print(f"\nEmail body saved to: {email_file}")
    
    print(f"\n{'='*60}")
    print(f"Processing Complete!")
    print(f"{'='*60}")
    print(f"Total transactions processed: {total_transactions}")
    print(f"  - PDF form: {pdf_count} transactions")
    if total_transactions > 10:
        print(f"  - CSV file: {total_transactions - 10} transactions")
    print(f"  - PDF summary: {summary_file}")
    print(f"  - Excelsior CSV: {excelsior_csv}")
    print(f"  - Email body: {email_file}")
    print(f"Output folder: {form_folder}")
    print(f"{'='*60}\n")

################################################################################################
# Execute the processing

if __name__ == "__main__":
    process_transactions(entry_data, form_folder, date_of_request, requester, phone_number,
                        company_name, group_number, df_data)